### ISSUE TITLE
[bug] cg upload vogue bioinfo-all error

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#1013]
When running `cg upload vogue bioinfo-all` some cases fail. This is due to recent changes in the statusdb data analysis field:

Error content:
```
Fetch latest version from bundle idealmutt
Fetching files from bundle idealmutt
Fetching files with tags in [multiqc-json]
Fetching files from version 27479
Traceback (most recent call last):
  File "/home/proj/bin/conda/envs/P_main/bin/cg", line 8, in <module>
    sys.exit(base())
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/upload/vogue.py", line 206, in bioinfo_all
    context.invoke(bioinfo, case_name=case_name, cleanup=True, target_load="all", dry=dry)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/upload/vogue.py", line 154, in bioinfo
    workflow_name, workflow_version = _get_analysis_workflow_details(store, case_name)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/upload/vogue.py", line 258, in _get_analysis_workflow_details
    return workflow_name.lower(), workflow_version
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by Mropat** [comment]
answered in #997
