### ISSUE TITLE
Issues placing orders on singular samples of trio cases

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/cg#1015]
## Description

A customer attempted to place a re-run order on a single sample out of a trio. This created a ticket however the case and order was not properly placed. When investigating the logs I found that:

```shell
2021-03-10 10:17:32 clinical-db.scilifelab.se cg.server.api[44910] INFO processing 'mip-dna' order: name='order_name' comment=None customer='cust002' samples=[{'internal_id': 'Internal_sample_ID', 'name': 'customer_sample_ID', 'data_
analysis': 'mip-dna', 'data_delivery': 'scout', 'application': 'WGTPCFC030', 'family_name': 'customer_case_ID', 'sex': 'male', 'source': 'other', 'priority': 'standard', 'formalin_fixation_time': None, 'post_formalin_fixation_time': Non
e, 'tissue_block_size': None, 'age_at_sampling': 'age_float', 'cohorts': [''], 'phenotype_terms': [''], 'synopsis': [''], 'comment': 'customer_case_ID Data finns customer_sample_ID', 'tumour': False, 'tumour_purity': None, 'capture_kit': None, 'c
ontainer': 'Tube', 'container_name': 'container_ID', 'well_position': None, 'volume': None, 'quantity': '', 'require_qcok': False, 'elution_buffer': None, 'panels': ['SKD'], 'status': 'affected', 'mother': 'mother_cust_ID', 'father':
 'father_cust_OD'}]
2021-03-10 10:17:33 clinical-db.scilifelab.se cg.meta.orders.ticket_handler[44910] INFO Could not detected ticket number in name order_name
2021-03-10 10:17:33 clinical-db.scilifelab.se urllib3.connectionpool[44910] DEBUG Starting new HTTPS connection (1): clinical-scilifelab.supportsystem.com:443
2021-03-10 10:18:01 clinical-db.scilifelab.se urllib3.connectionpool[44910] DEBUG https://clinical-scilifelab.supportsystem.com:443 "POST /api/tickets.json HTTP/1.1" 201 6
2021-03-10 10:18:01 clinical-db.scilifelab.se cg.meta.orders.ticket_handler[44910] INFO 689193: opened new ticket
2021-03-10 10:18:01 [44910] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/sync.py", line 93, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/sync.py", line 134, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/site-packages/cg/server/api.py", line 72, in submit_order
    user_mail=g.current_user.email,
  File "/home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/site-packages/cg/meta/orders/api.py", line 60, in submit
    return order_func(order)
  File "/home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/site-packages/cg/meta/orders/api.py", line 134, in _submit_mip_dna
    return self._submit_case_samples(order)
  File "/home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/site-packages/cg/meta/orders/api.py", line 120, in _submit_case_samples
    result = self._process_case_samples(order)
  File "/home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/site-packages/cg/meta/orders/api.py", line 183, in _process_case_samples
    cases=status_data["families"],
  File "/home/hiseq.clinical/miniconda/envs/prod170926/lib/python3.6/site-packages/cg/meta/orders/status.py", line 257, in store_cases
    mother_obj = family_samples[sample["mother"]] if sample.get("mother") else None
KeyError: 'mother_cust_ID'
```

## Suggested solution

It seems like the order is trying to fetch the mother from the new case, however the sample was ordered as a singlet thus no mother is connected to it.

## This can be closed when

Customers can order a re-run of a single sample from a trio case.

**Comment by karlnyr** [comment]
I assigned this to you @patrikgrenfeldt, I hope that is correct

**Comment by barrystokman** [comment]
Solution: for an existing sample the trio check should be handled in the back end: skip trio check for existing sample unless a single, existing sample is added to a trio.

**Comment by barrystokman** [comment]
@Clinical-Genomics/data-analysis  How often does this occur?

**Comment by henningonsbring** [comment]
I have never seen this error before. And it should be rare, I do not understand why you should exclude two other persons from a trio, the two other persons really helps a lot in the analysis.

**Comment by henrikstranneheim** [comment]
Yes, I agree with you Henning that it does not make a lot of sense from an analysis point of view. But the system should handle this more gracefully.

It is good to know that this is a rare case. Might even be that the customer did not remember a trio existed.

**Comment by karlnyr** [comment]
From what I have gathered it has been requested by customers to perform analysis on single samples in a trio.
