### ISSUE TITLE
Failure for NIPT/database_setup.py --flowcell_ids flowcells

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/cg#1051]
## Description

Cron <hiseq.clinical@hasta> $CRONIC /home/proj/bin/conda/envs/nipt/bin/python /home/proj/production/bin/git/NIPT/database_setup.py --flowcell_ids `for i in /home/proj/production/flowcells/2500/nipt/*_*; do echo $i|cut -d '/' -f 5;done`

Cronic detected failure for the command:
/home/proj/bin/conda/envs/nipt/bin/python /home/proj/production/bin/git/NIPT/database_setup.py --flowcell_ids flowcells

```
Traceback (most recent call last):
 File "/home/proj/production/bin/git/NIPT/database_setup.py", line 14, in <module>
   from extentions import app
 File "/home/proj/production/bin/git/NIPT/extentions.py", line 1, in <module>
   from flask import Flask
ImportError: No module named flask

RESULT CODE: 1
```

## Suggested solution

*Write here if there is a suggested way to solve the issue*

## This can be closed when

- [ ] When the crontab is working again

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by henrikstranneheim** [comment]
@mayabrandi @barrystokman Is this related to the migration?
