### ISSUE TITLE
CG upload auto crontab error 

### ISSUE THREAD

**Issue by Mropat** [Clinical-Genomics/cg#1058]
## Description

When analysis is uploaded to Scout via `cg upload auto`, we set timestamp in statusDB field analysis_upload_started_at in table Analysis
The cron will loop through all analyses where field analysis_uploaded_at is not set. If upload is completed, it will be updated
If not, and it has been >24h, the error is thrown:

```
----------------- UPLOAD ----------------------
2021-03-22 09:55:17 hasta.scilifelab.se cg.cli.upload.base[59064] ERROR Uploading family failed: decenttuna
2021-03-22 09:55:17 hasta.scilifelab.se cg.cli.upload.base[59064] ERROR Traceback (most recent call last):
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/upload/base.py", line 145, in auto
    context.invoke(upload, family_id=internal_id)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/upload/base.py", line 71, in upload
    f"The upload started at {analysis_obj.upload_started_at} "
cg.exc.AnalysisUploadError
```

It is caused by this piece of code:
https://github.com/Clinical-Genomics/cg/blob/b0ebab69dbd8a52ffcc148a1d46c842f797bb62b/cg/cli/upload/base.py#L66

However, the way the error is raised and arguments passed, the entire error message will not be displayedand it becomes very unclear to end user what the problem is

## Suggested solution

Fix error message
Optional(Find a way for scout to inform cg when upload fails and why, to better automate default management of such error)

## This can be closed when
crontab errors are formatted better

**Comment by Mropat** [comment]
removing link, this is a different issue

**Comment by Mropat** [comment]
Will not be fixed in this version of cg
