### ISSUE TITLE
cg upload scout fails for balsamic TN

### ISSUE THREAD

**Issue by Mropat** [Clinical-Genomics/cg#1118]
## Description

`cg upload scout` fails for balsamic TN

```
[0|0|578] 1d [karl.nyren@hasta:/home/proj/production/cancer/cases] [P_main] 54m57s $ cg upload scout petwolf
----------------- UPLOAD ----------------------
----------------- SCOUT -----------------------
----------------- CREATE CONFIG -----------------------
Fetching family object
Create load config
Generate scout load config
Fetch latest version from bundle petwolf
Found pipeline balsamic
Build load config for balsamic case
Adding synopsis string to scout load config
Including cohorts to scout load config
Adding phenotype terms to scout load config
Including BALSAMIC specific case level files
Fetch file with tags {'vcf-snv-clinical'}
Could not find any files matching the tags
Traceback (most recent call last):
  File "/home/proj/bin/conda/envs/P_main/bin/cg", line 8, in <module>
    sys.exit(base())
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/upload/scout.py", line 39, in scout
    create_scout_load_config, case_id=case_id, print_console=print_console, re_upload=re_upload
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/upload/scout.py", line 65, in create_scout_load_config
    scout_load_config: ScoutLoadConfig = scout_upload_api.generate_config(case_obj.analyses[0])
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/meta/upload/scout/scoutapi.py", line 66, in generate_config
    config_builder.build_load_config()
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/meta/upload/scout/balsamic_config_builder.py", line 69, in build_load_config
    self.include_case_files()
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/meta/upload/scout/balsamic_config_builder.py", line 28, in include_case_files
    self.load_config.vcf_cancer = self.fetch_file_from_hk(self.case_tags.snv_vcf)
  File "pydantic/main.py", line 439, in pydantic.main.BaseModel.__setattr__
pydantic.error_wrappers.ValidationError: 1 validation error for BalsamicLoadConfig
vcf_cancer
  Vcf can not be none (type=value_error)

```
## Suggested solution

Ensure hermes tags and cg upload are correct for Balsamic 7.x.x

## This can be closed when

It is possible to correctly upload any balsamic case to Scout with `cg upload scout`

**Comment by hassanfa** [comment]
That's something for me. 7.x.x will hopefully resolve it. 🤞🏽
