### ISSUE TITLE
cg clean scout-finished-cases -y --days-old 300 is broken

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/cg#1459]
## Description

Crontab runs: [/home/proj/production/servers/resources/hasta.scilifelab.se/crontabs/cron-cg-clean.sh](https://github.com/Clinical-Genomics/servers/blob/master/resources/hasta.scilifelab.se/crontabs/cron-cg-clean.sh)

To clean all analysis pipeline directories and a selection of alignement files from Housekeeper.

The script has the option: `set -o errexit` set, which means that it will stop the process if it encounters an error.

Currently, the `cg clean scout-finished-cases -y --days-old 300` is the first process that is executed and it has been failing for some time on:

```
2022-04-06 01:01:17 [hasta.scilifelab.se](http://hasta.scilifelab.se/) cg.apps.scout.scoutapi[48588] INFO Validating case truetiger
Traceback (most recent call last):
 File "/home/proj/bin/conda/envs/P_main/bin/cg", line 8, in <module>
   sys.exit(base())
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 722, in __call__
   return self.main(*args, **kwargs)
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 697, in main
   rv = self.invoke(ctx)
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
   return _process_result(sub_ctx.command.invoke(sub_ctx))
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
   return _process_result(sub_ctx.command.invoke(sub_ctx))
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 895, in invoke
   return ctx.invoke(self.callback, **ctx.params)
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
   return callback(*args, **kwargs)
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
   return f(get_current_context(), *args, **kwargs)
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/clean.py", line 123, in scout_finished_cases
   cases: List[ScoutExportCase] = scout_api.get_cases(status=status, reruns=False)
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/apps/scout/scoutapi.py", line 183, in get_cases
   case_obj = ScoutExportCase(**case_export)
 File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ScoutExportCase
diagnosis_phenotypes -> 0
 value is not a valid integer (type=type_error.integer)
```

Cg expects:
```
diagnosis_phenotypes: Optional[List[int]]
```
The format of diagnosis_phenotypes, before, was a list of integers corresponding to the OMIM disease numbers:
example : [611277, 604169]

But gets form the Scout JSON export:

<img width="848" alt="Screenshot 2022-04-11 at 08 59 34" src="https://user-images.githubusercontent.com/584738/162682104-822ceea9-1b30-4b77-b262-88a8631606d3.png">

Now it became: a list of dictionaries.
This allows Scout to assign OMIM terms in Scout to specific individuals instead of at the more general level, as it was before.
The new format is saved whenever a user assigns OMIM cases to a new case or edits the OMIM terms for an old case.

The thing is that old cases with OMIM saved as a list of integers are still in the database, and their format is still a list of integers

> NOTE
> 
> This means that the the cleaning of the analysis dirs have not been done for some time.

## Suggested solution

1. We should change Scouts export to always be a list of dictionaries to make it predictable what will be exported
2. We should change cg to always expect the new format of list of dictionaries

## This can be closed when

- [ ] When `cg clean scout-finished-cases -y --days-old 300` works again

**Comment by henrikstranneheim** [comment]
Since hasta is at 90% storage utilisation - I manually started:
```
[0|0|3454] 7d [hiseq.clinical@hasta:~] [P_main] 11m53s 1 $ cg clean mip-past-run-dirs "$(date -d '-21days' +'%Y-%m-%d')" -y
Cleaning 1109 analyses created before 2022-03-21 00:00:00
Cleaning mip-dna output for greatimp
.
.
.
```

The cleaning is currently running

**Comment by henrikstranneheim** [comment]
@northwestwitch FYI!

**Comment by henrikstranneheim** [comment]
After MIP analysis dir cleaning: 
```
hasta                   2.1P  1.6P  521T  76% /home
```

**Comment by vwirta** [comment]
Party time!

**Comment by henrikstranneheim** [comment]
```
[0|3700|3815] 7d [hiseq.clinical@hasta:~] [P_main] 1h9m40s 1 $ cg clean balsamic-past-run-dirs "$(date -d '-45days' +'%Y-%m-%d')" -y
Cleaning 0 analyses created before 2022-02-25 00:00:00
Done cleaning balsamic output
[27|3815|3941] 7d [hiseq.clinical@hasta:~] [P_main] 22s $ cg clean fluffy-past-run-dirs "$(date -d '-21days' +'%Y-%m-%d')" -y
Set root dir to /home/proj/production/nipt/cases
Cleaning 21 analyses created before 2022-03-21 00:00:00
[26|3941|4063] 7d [hiseq.clinical@hasta:~] [P_main] 1m27s 1 $ cg clean mutant-past-run-dirs "$(date -d '-21days' +'%Y-%m-%d')" -y
Cleaning 105 analyses created before 2022-03-21 00:00:00
```

**Comment by henrikstranneheim** [comment]
```
hasta                   2.1P  1.6P  537T  75% /home
```
