### ISSUE TITLE
Database connection dropped

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/cg#2008]
## Description
Occasionally we get 500 errors due to the database connection being dropped. We should look into handling this more gracefully. Here is an example log with the error:

```
10.0.2.100 - - [05/May/2023:05:41:34 +0200] "GET /admin/organism/ HTTP/1.0" 500 0 "-" "-"
(Background on this error at: http://sqlalche.me/e/13/e3q8)
[parameters: {'email_1': 'sebastian.allard@scilifelab.se', 'param_1': 1}]
 LIMIT %(param_1)s]
WHERE user.email = %(email_1)s
FROM user
[SQL: SELECT user.id AS user_id, user.name AS user_name, user.email AS user_email, user.is_admin AS user_is_admin, user.order_portal_login AS user_>
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")
    CR.CR_SERVER_GONE_ERROR, "MySQL server has gone away (%r)" % (e,)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 764, in _write_bytes
    self._write_bytes(packet)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 818, in _execute_command
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 548, in query
    conn.query(q)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 325, in _query
    result = self._query(query)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 158, in execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    distilled_params,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return list(res)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3203, in __getitem__
    ret = list(self[0:1])
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3429, in first
    filter_functions=[UserFilter.FILTER_BY_EMAIL],
  File "/home/src/app/cg/store/api/find_basic_data.py", line 209, in get_user_by_email
    user = db.get_user_by_email(email=session.get("user_email"))
  File "/home/src/app/cg/server/admin.py", line 23, in is_accessible
    if not self.is_accessible():
  File "/usr/local/lib/python3.7/site-packages/flask_admin/base.py", line 353, in _handle_view
    abort = self._handle_view(f.__name__, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_admin/base.py", line 65, in inner
    return self.view_functions[rule.endpoint](**req.view_args)
```

## Suggested solution
SqlAlchemy has some suggestions for handling disconnects: 
https://docs.sqlalchemy.org/en/13/core/pooling.html#dealing-with-disconnects

## Blocked by

**Comment by henrikstranneheim** [comment]
@seallard Was this fixed by not using the cache?

**Comment by seallard** [comment]
@henrikstranneheim I think that resolved the issue of the service having to be restarted (right @Vince-janv?). Going through the logs I can still find errors like the one above. So I think this is unrelated. For instance

```
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]: (Background on this error at: http://sqlalche.me/e/13/e3q8)
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]: [parameters: {'tag_1': 'VWGDPTR001', 'param_1': 1}]
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:  LIMIT %(param_1)s]
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]: WHERE application.tag = %(tag_1)s
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]: FROM application
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]: [SQL: SELECT application.id AS application_id, application.tag AS application_tag, application.prep_category AS application_prep_category, application.is_external AS applicatio>
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]: sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:     CR.CR_SERVER_GONE_ERROR, "MySQL server has gone away (%r)" % (e,)
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 764, in _write_bytes
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:     self._write_bytes(packet)
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 818, in _execute_command
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:     self._execute_command(COMMAND.COM_QUERY, sql)
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 548, in query
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:     conn.query(q)
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:   File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 325, in _query
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:     result = self._query(query)
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:   File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 158, in execute
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:     cursor.execute(statement, parameters)
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:     cursor, statement, parameters, context
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:     raise exception
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:     e, statement, parameters, cursor, context
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:     distilled_params,
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:     return connection._execute_clauseelement(self, multiparams, params)
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:     return meth(self, multiparams, params)
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:     result = conn.execute(querycontext.statement, self._params)
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:     return self._execute_and_instances(context)
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:     return list(res)
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3203, in __getitem__
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:     ret = list(self[0:1])
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3429, in first
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:     tag=tag,
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:   File "/home/src/app/cg/store/api/find_basic_data.py", line 47, in get_application_by_tag
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:     application: Application = db.get_application_by_tag(tag=tag)
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:   File "/home/src/app/cg/server/api.py", line 461, in parse_application
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:     return route_function(*args, **kwargs)
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:   File "/home/src/app/cg/server/api.py", line 79, in public_endpoint
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:     return self.view_functions[rule.endpoint](**req.view_args)
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:     rv = self.dispatch_request()
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:     raise value
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:     reraise(exc_type, exc_value, tb)
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:     return cors_after_request(app.make_response(f(*args, **kwargs)))
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:   File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:     rv = self.handle_user_exception(e)
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:     response = self.full_dispatch_request()
May 17 10:45:36 cg-vm1.scilifelab.se podman[1528240]:   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
```

**Comment by seallard** [comment]
Still occurring intermittently 
```
-- Logs begin at Fri 2023-06-16 13:14:12 CEST, end at Fri 2023-08-11 10:02:10 CEST. --
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]: 10.0.2.100 - - [11/Aug/2023:10:02:10 +0200] "GET /api/v1/flowcells/H27CLDRX3/sequencing_metrics HTTP/1.0" 500 0 "-" "-"
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]: (Background on this error at: http://sqlalche.me/e/13/e3q8)
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]: [parameters: {'email_1': 'clinical-apps@appspot.gserviceaccount.com', 'param_1': 1}]
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:  LIMIT %(param_1)s]
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]: WHERE user.email = %(email_1)s
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]: FROM user
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]: [SQL: SELECT user.id AS user_id, user.name AS user_name, user.email AS user_email, user.is_admin AS user_is_admin, user.order_portal_login AS user_order_portal_login
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]: sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     CR.CR_SERVER_GONE_ERROR, f"MySQL server has gone away ({e!r})"
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 807, in _write_bytes
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     self._write_bytes(packet)
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 861, in _execute_command
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     self._execute_command(COMMAND.COM_QUERY, sql)
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 557, in query
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     conn.query(q)
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 322, in _query
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     result = self._query(query)
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 153, in execute
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     cursor.execute(statement, parameters)
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     cursor, statement, parameters, context
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     raise exception
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     e, statement, parameters, cursor, context
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     distilled_params,
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     return connection._execute_clauseelement(self, multiparams, params)
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     return meth(self, multiparams, params)
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     result = conn.execute(querycontext.statement, self._params)
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     return self._execute_and_instances(context)
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     return list(res)
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3203, in __getitem__
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     ret = list(self[0:1])
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3429, in first
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     filter_functions=[UserFilter.FILTER_BY_EMAIL],
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/home/src/app/cg/store/api/find_basic_data.py", line 176, in get_user_by_email
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     user: User = db.get_user_by_email(user_data["email"])
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/home/src/app/cg/server/api.py", line 128, in before_request
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     rv = func()
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2242, in preprocess_request
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     rv = self.preprocess_request()
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1948, in full_dispatch_request
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     raise value
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     reraise(exc_type, exc_value, tb)
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     return cors_after_request(app.make_response(f(*args, **kwargs)))
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 176, in wrapped_function
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     raise value
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     reraise(exc_type, exc_value, tb)
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     return cors_after_request(app.make_response(f(*args, **kwargs)))
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 176, in wrapped_function
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     rv = self.handle_user_exception(e)
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     response = self.full_dispatch_request()
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     raise value
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     reraise(exc_type, exc_value, tb)
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     return cors_after_request(app.make_response(f(*args, **kwargs)))
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 176, in wrapped_function
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     response = self.handle_exception(e)
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     return self.wsgi_app(environ, start_response)
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     respiter = self.wsgi(environ, resp.start_response)
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 334, in handle_request
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     keepalive = self.handle_request(req, conn)
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 282, in handle
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]: Traceback (most recent call last):
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]: [1B blob data]
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]: The above exception was the direct cause of the following exception:
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]: [1B blob data]
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]: pymysql.err.OperationalError: (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     CR.CR_SERVER_GONE_ERROR, f"MySQL server has gone away ({e!r})"
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 807, in _write_bytes
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     self._write_bytes(packet)
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 861, in _execute_command
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     self._execute_command(COMMAND.COM_QUERY, sql)
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 557, in query
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     conn.query(q)
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 322, in _query
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     result = self._query(query)
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 153, in execute
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     cursor.execute(statement, parameters)
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     cursor, statement, parameters, context
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]: Traceback (most recent call last):
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]: [1B blob data]
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]: During handling of the above exception, another exception occurred:
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]: [1B blob data]
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]: BrokenPipeError: [Errno 32] Broken pipe
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:     self._sock.sendall(data)
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]:   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 803, in _write_bytes
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]: Traceback (most recent call last):
Aug 11 10:02:10 cg-vm1.scilifelab.se podman[1966122]: [2023-08-11 10:02:10 +0200] [5] [ERROR] Error handling request /api/v1/flowcells/H27CLDRX3/sequencing_metrics
```

**Comment by seallard** [comment]
Should have been resolved now, will re-open if the issue occurs again
