### ISSUE TITLE
Fetching flow cells from PDC fails

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/cg#2114]
## Description
For two flow cells, it seems like they can not be retrieved from the PDC. Specifically flow cell `HHH5TDSX2` and `HKJL7DSXY`. Here is an example of a log where the retrieval of the `HHH5TDSX2` flow cell from PDC fails:

```
2023-03-13 16:43:40 hasta.scilifelab.se cg.meta.backup.backup[171712] INFO HHH5TDSX2: retrieving from PDC
2023-03-13 16:43:40 hasta.scilifelab.se cg.utils.commands[171712] INFO Running command /bin/dsmc q archive /home/hiseq.clinical/ENCRYPT/*HHH5TDSX2*
2023-03-13 16:43:56 hasta.scilifelab.se cg.utils.commands[171712] INFO Running command /bin/dsmc q archive /mnt/hds/proj/bioinfo/TO_PDC/*HHH5TDSX2*
2023-03-13 16:44:01 hasta.scilifelab.se cg.utils.commands[171712] CRITICAL Call ['/bin/dsmc', 'q', 'archive', '/mnt/hds/proj/bioinfo/TO_PDC/*HHH5TDSX2*'] exit with a non zero exit code
2023-03-13 16:44:01 hasta.scilifelab.se cg.utils.commands[171712] CRITICAL ANS1092W No files matching search criteria were found
2023-03-13 16:44:01 hasta.scilifelab.se cg.meta.backup.backup[171712] INFO No archived files found for pdc query ['/home/hiseq.clinical/ENCRYPT/*HHH5TDSX2*', '/mnt/hds/proj/bioinfo/TO_PDC/*HHH5TDSX2*'], testing legacy directory
2023-03-13 16:44:01 hasta.scilifelab.se cg.meta.backup.backup[171712] INFO Found archived files for pdc queries ['/home/hiseq.clinical/ENCRYPT/*HHH5TDSX2*', '/mnt/hds/proj/bioinfo/TO_PDC/*HHH5TDSX2*']
2023-03-13 16:44:01 hasta.scilifelab.se cg.meta.backup.backup[171712] INFO Encryption key found: /home/hiseq.clinical/ENCRYPT/211029_A00621_0522_AHHH5TDSX2.key.gpg
2023-03-13 16:44:01 hasta.scilifelab.se cg.meta.backup.backup[171712] INFO Flow cell found: /home/hiseq.clinical/ENCRYPT/211029_A00621_0522_AHHH5TDSX2.tar.gz.gpg
2023-03-13 16:44:01 hasta.scilifelab.se cg.utils.commands[171712] INFO Running command /bin/dsmc retrieve -replace=yes /home/hiseq.clinical/ENCRYPT/211029_A00621_0522_AHHH5TDSX2.key.gpg /home/proj/production/flowcells/novaseq/runs/211029_A00621_0522_AHHH5TDSX2.key.gpg
2023-03-13 16:45:31 hasta.scilifelab.se cg.utils.commands[171712] CRITICAL Call ['/bin/dsmc', 'retrieve', '-replace=yes', '/home/hiseq.clinical/ENCRYPT/211029_A00621_0522_AHHH5TDSX2.key.gpg', '/home/proj/production/flowcells/novaseq/runs/211029_A00621_0522_AHHH5TDSX2.key.gpg'] exit with a non zero exit code
2023-03-13 16:45:31 hasta.scilifelab.se cg.utils.commands[171712] CRITICAL 
2023-03-13 16:45:31 hasta.scilifelab.se cg.meta.backup.backup[171712] WARNING WARNING for retrieval of encryption key of flow cell HHH5TDSX2, please check dsmerror.log
2023-03-13 16:45:31 hasta.scilifelab.se cg.utils.commands[171712] INFO Running command /bin/dsmc retrieve -replace=yes /home/hiseq.clinical/ENCRYPT/211029_A00621_0522_AHHH5TDSX2.tar.gz.gpg /home/proj/production/flowcells/novaseq/runs/211029_A00621_0522_AHHH5TDSX2.tar.gz.gpg
2023-03-13 18:34:15 hasta.scilifelab.se cg.utils.commands[171712] CRITICAL Call ['/bin/dsmc', 'retrieve', '-replace=yes', '/home/hiseq.clinical/ENCRYPT/211029_A00621_0522_AHHH5TDSX2.tar.gz.gpg', '/home/proj/production/flowcells/novaseq/runs/211029_A00621_0522_AHHH5TDSX2.tar.gz.gpg'] exit with a non zero exit code
2023-03-13 18:34:15 hasta.scilifelab.se cg.utils.commands[171712] CRITICAL 
2023-03-13 18:34:15 hasta.scilifelab.se cg.meta.backup.backup[171712] WARNING WARNING for retrieval of flow cell HHH5TDSX2, please check dsmerror.log
2023-03-13 18:34:15 hasta.scilifelab.se cg.meta.backup.backup[171712] INFO Status for flow cell HHH5TDSX2 set to retrieved
2023-03-13 18:34:15 hasta.scilifelab.se cg.meta.encryption.encryption[171712] INFO Starting GPG command:
2023-03-13 18:34:15 hasta.scilifelab.se cg.meta.encryption.encryption[171712] INFO /bin/gpg --decrypt --batch --cipher-algo AES256 --passphrase  Secret -o /home/proj/production/flowcells/novaseq/runs/211029_A00621_0522_AHHH5TDSX2.key /home/proj/production/flowcells/novaseq/runs/211029_A00621_0522_AHHH5TDSX2.key.gpg
2023-03-13 18:34:15 hasta.scilifelab.se cg.utils.commands[171712] INFO Running command /bin/gpg --decrypt --batch --cipher-algo AES256 --passphrase Secret -o /home/proj/production/flowcells/novaseq/runs/211029_A00621_0522_AHHH5TDSX2.key /home/proj/production/flowcells/novaseq/runs/211029_A00621_0522_AHHH5TDSX2.key.gpg
2023-03-13 18:34:15 hasta.scilifelab.se cg.meta.encryption.encryption[171712] INFO Starting GPG command:
2023-03-13 18:34:15 hasta.scilifelab.se cg.meta.encryption.encryption[171712] INFO /bin/gpg --decrypt --cipher-algo AES256 --batch --passphrase-file /home/proj/production/flowcells/novaseq/runs/211029_A00621_0522_AHHH5TDSX2.key -o /home/proj/production/flowcells/novaseq/runs/211029_A00621_0522_AHHH5TDSX2.tar.gz /home/proj/productio
n/flowcells/novaseq/runs/211029_A00621_0522_AHHH5TDSX2.tar.gz.gpg
2023-03-13 18:34:15 hasta.scilifelab.se cg.utils.commands[171712] INFO Running command /bin/gpg --decrypt --cipher-algo AES256 --batch --passphrase-file /home/proj/production/flowcells/novaseq/runs/211029_A00621_0522_AHHH5TDSX2.key -o /home/proj/production/flowcells/novaseq/runs/211029_A00621_0522_AHHH5TDSX2.tar.gz /home/proj/produ
ction/flowcells/novaseq/runs/211029_A00621_0522_AHHH5TDSX2.tar.gz.gpg
2023-03-14 02:49:22 hasta.scilifelab.se cg.utils.commands[171712] CRITICAL Call ['/bin/gpg', '--decrypt', '--cipher-algo', <CipherAlgorithm.AES256: 'AES256'>, '--batch', '--passphrase-file', '/home/proj/production/flowcells/novaseq/runs/211029_A00621_0522_AHHH5TDSX2.key', '-o', '/home/proj/production/flowcells/novaseq/runs/211029_A
00621_0522_AHHH5TDSX2.tar.gz', '/home/proj/production/flowcells/novaseq/runs/211029_A00621_0522_AHHH5TDSX2.tar.gz.gpg'] exit with a non zero exit code
2023-03-14 02:49:22 hasta.scilifelab.se cg.utils.commands[171712] CRITICAL gpg: AES256 encrypted data
gpg: encrypted with 1 passphrase
gpg: decryption failed: Bad signature
2023-03-14 02:49:22 hasta.scilifelab.se cg.meta.backup.backup[171712] ERROR Decryption failed: None
Traceback (most recent call last):
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/cg/meta/backup/backup.py", line 122, in _process_flow_cell
    ) = self.decrypt_flow_cell(archived_flow_cell, archived_key, run_dir)
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/cg/meta/backup/backup.py", line 201, in decrypt_flow_cell
    self.encryption_api.run_gpg_command(decryption_command)
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/cg/meta/encryption/encryption.py", line 34, in run_gpg_command
    self.process.run_command(command, dry_run=self.dry_run)
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/cg/utils/commands.py", line 108, in run_command
    raise CalledProcessError(res.returncode, command)
subprocess.CalledProcessError: Command '['/bin/gpg', '--decrypt', '--cipher-algo', <CipherAlgorithm.AES256: 'AES256'>, '--batch', '--passphrase-file', '/home/proj/production/flowcells/novaseq/runs/211029_A00621_0522_AHHH5TDSX2.key', '-o', '/home/proj/production/flowcells/novaseq/runs/211029_A00621_0522_AHHH5TDSX2.tar.gz', '/home/pr
oj/production/flowcells/novaseq/runs/211029_A00621_0522_AHHH5TDSX2.tar.gz.gpg']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/pymysql/connections.py", line 692, in _read_packet
    packet_header = self._read_bytes(4)
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/pymysql/connections.py", line 749, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query"
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/proj/production/bin/miniconda3/envs/P_main/bin/cg", line 8, in <module>
    sys.exit(base())
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/cg/cli/backup.py", line 62, in fetch_flow_cell
    retrieval_time: Optional[float] = backup_api.fetch_flow_cell(flow_cell=flow_cell)
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/cg/meta/backup/backup.py", line 102, in fetch_flow_cell
    archived_flow_cell=archived_flow_cell,
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/cg/meta/backup/backup.py", line 133, in _process_flow_cell
    self.status.commit()
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1046, in commit
    self.transaction.commit()
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 504, in commit
    self._prepare_impl()
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
    self.session.flush()
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2540, in flush
    self._flush(objects)
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2682, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2642, in _flush
    flush_context.execute()
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    update,
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 995, in _emit_update_statements
    statement, multiparams
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/pymysql/connections.py", line 692, in _read_packet
    packet_header = self._read_bytes(4)
  File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/pymysql/connections.py", line 749, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query"
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
[SQL: UPDATE flowcell SET `status`=%(status)s, updated_at=%(updated_at)s WHERE flowcell.id = %(flowcell_id)s]
[parameters: {'status': 'requested', 'updated_at': datetime.datetime(2023, 3, 14, 2, 49, 22, 585364), 'flowcell_id': 1617}]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

RESULT CODE: 1
```

## Suggested solution

*Write here if there is a suggested way to solve the issue*

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by seallard** [comment]
The issue can be reproduced by running: 
```
cg backup fetch-flow-cell -f HHH5TDSX2
```

**Comment by seallard** [comment]
@Vince-janv and @karlnyr, please have a look at this when you are back. The reanalysis of these two flow cells have been delayed by 1.5 months or so

**Comment by beatrizsavinhas** [comment]
I believe the same problem is happening with flowcell `HL532DSXY` as well which is delaying the delivery of a re-run.

**Comment by Vince-janv** [comment]
> I believe the same problem is happening with flowcell `HL532DSXY` as well which is delaying the delivery of a re-run.

Demultiplexing of `HL532DSXY` is now running after some manual handling

**Comment by Vince-janv** [comment]
For future debugging the flow cell had already been decrypted but not untared. I did the following:

1.  untared it with: `tar -xf <flow_cell_run_dir>/211029_A00621_0522_AHHH5TDSX2.tar.gz --exclude=RTAComplete.txt --exclude=demuxstarted.txt --exclude=Thumbnail_Images -C <flow_cell_run_dir>` (in a tmux session)
2.  touched the RTAComplete.txt
3. removed the tar and gpg files

These are basically all the operations from [this line](https://github.com/Clinical-Genomics/cg/blob/097e3e0204c242c8f904986a5a64a8e29c949b2a/cg/meta/backup/backup.py#L124) and onwards in `cg.meta.backup.backup.BackupAPI._process_flow_cell`

**Comment by beatrizsavinhas** [comment]
Flow cells `HKK23DSXY` and `H3MG5DSX2` are stuck as "requested" in StatusDB.

We have the following cron error for flow cell `HKK23DSXY` from 29 Aug 2023, 23:04:

```
2023-08-29 21:43:33 [hasta.scilifelab.se](http://hasta.scilifelab.se/) cg.meta.backup.backup[56113] INFO HKK23DSXY: retrieving from PDC
2023-08-29 21:43:33 [hasta.scilifelab.se](http://hasta.scilifelab.se/) cg.utils.commands[56113] INFO Running command /bin/dsmc q archive /home/hiseq.clinical/ENCRYPT/*HKK23DSXY*
2023-08-29 21:43:36 [hasta.scilifelab.se](http://hasta.scilifelab.se/) cg.utils.commands[56113] INFO Running command /bin/dsmc q archive /mnt/hds/proj/bioinfo/TO_PDC/*HKK23DSXY*
2023-08-29 21:43:38 [hasta.scilifelab.se](http://hasta.scilifelab.se/) cg.utils.commands[56113] CRITICAL Call ['/bin/dsmc', 'q', 'archive', '/mnt/hds/proj/bioinfo/TO_PDC/*HKK23DSXY*'] exit with a non zero exit code
2023-08-29 21:43:38 [hasta.scilifelab.se](http://hasta.scilifelab.se/) cg.utils.commands[56113] CRITICAL ANS1092W No files matching search criteria were found
2023-08-29 21:43:38 [hasta.scilifelab.se](http://hasta.scilifelab.se/) cg.meta.backup.backup[56113] INFO No archived files found for pdc query ['/home/hiseq.clinical/ENCRYPT/*HKK23DSXY*', '/mnt/hds/proj/bioinfo/TO_PDC/*HKK23DSXY*'], testing legacy directory
2023-08-29 21:43:38 [hasta.scilifelab.se](http://hasta.scilifelab.se/) cg.meta.backup.backup[56113] INFO Found archived files for pdc queries ['/home/hiseq.clinical/ENCRYPT/*HKK23DSXY*', '/mnt/hds/proj/bioinfo/TO_PDC/*HKK23DSXY*']
2023-08-29 21:43:38 [hasta.scilifelab.se](http://hasta.scilifelab.se/) cg.meta.backup.backup[56113] INFO Encryption key found: /home/hiseq.clinical/ENCRYPT/210115_A00689_0215_BHKK23DSXY.key.gpg
2023-08-29 21:43:38 [hasta.scilifelab.se](http://hasta.scilifelab.se/) cg.meta.backup.backup[56113] INFO Flow cell found: /home/hiseq.clinical/ENCRYPT/210115_A00689_0215_BHKK23DSXY.tar.gz.gpg
2023-08-29 21:43:38 [hasta.scilifelab.se](http://hasta.scilifelab.se/) cg.utils.commands[56113] INFO Running command /bin/dsmc retrieve -replace=yes /home/hiseq.clinical/ENCRYPT/210115_A00689_0215_BHKK23DSXY.key.gpg /home/proj/production/flow_cells/210115_A00689_0215_BHKK23DSXY.key.gpg
2023-08-29 21:43:44 [hasta.scilifelab.se](http://hasta.scilifelab.se/) cg.utils.commands[56113] CRITICAL Call ['/bin/dsmc', 'retrieve', '-replace=yes', '/home/hiseq.clinical/ENCRYPT/210115_A00689_0215_BHKK23DSXY.key.gpg', '/home/proj/production/flow_cells/210115_A00689_0215_BHKK23DSXY.key.gpg'] exit with a non zero exit code
2023-08-29 21:43:44 [hasta.scilifelab.se](http://hasta.scilifelab.se/) cg.utils.commands[56113] CRITICAL
2023-08-29 21:43:44 [hasta.scilifelab.se](http://hasta.scilifelab.se/) cg.meta.backup.backup[56113] WARNING WARNING for retrieval of encryption key of flow cell HKK23DSXY, please check dsmerror.log
2023-08-29 21:43:44 [hasta.scilifelab.se](http://hasta.scilifelab.se/) cg.utils.commands[56113] INFO Running command /bin/dsmc retrieve -replace=yes /home/hiseq.clinical/ENCRYPT/210115_A00689_0215_BHKK23DSXY.tar.gz.gpg /home/proj/production/flow_cells/210115_A00689_0215_BHKK23DSXY.tar.gz.gpg
2023-08-29 23:04:41 [hasta.scilifelab.se](http://hasta.scilifelab.se/) cg.utils.commands[56113] CRITICAL Call ['/bin/dsmc', 'retrieve', '-replace=yes', '/home/hiseq.clinical/ENCRYPT/210115_A00689_0215_BHKK23DSXY.tar.gz.gpg', '/home/proj/production/flow_cells/210115_A00689_0215_BHKK23DSXY.tar.gz.gpg'] exit with a non zero exit code
2023-08-29 23:04:41 [hasta.scilifelab.se](http://hasta.scilifelab.se/) cg.utils.commands[56113] CRITICAL
2023-08-29 23:04:41 [hasta.scilifelab.se](http://hasta.scilifelab.se/) cg.meta.backup.backup[56113] WARNING WARNING for retrieval of flow cell HKK23DSXY, please check dsmerror.log
2023-08-29 23:04:41 [hasta.scilifelab.se](http://hasta.scilifelab.se/) cg.meta.backup.backup[56113] INFO Status for flow cell HKK23DSXY set to retrieved
2023-08-29 23:04:41 [hasta.scilifelab.se](http://hasta.scilifelab.se/) cg.meta.encryption.encryption[56113] INFO Starting GPG command:
2023-08-29 23:04:41 [hasta.scilifelab.se](http://hasta.scilifelab.se/) cg.meta.encryption.encryption[56113] INFO /bin/gpg --decrypt --batch --cipher-algo AES256 --passphrase Clinical Genomics -o /home/proj/production/flow_cells/210115_A00689_0215_BHKK23DSXY.key /home/proj/production/flow_cells/210115_A00689_0215_BHKK23DSXY.key.gpg
2023-08-29 23:04:41 [hasta.scilifelab.se](http://hasta.scilifelab.se/) cg.utils.commands[56113] INFO Running command /bin/gpg --decrypt --batch --cipher-algo AES256 --passphrase Clinical Genomics -o /home/proj/production/flow_cells/210115_A00689_0215_BHKK23DSXY.key /home/proj/production/flow_cells/210115_A00689_0215_BHKK23DSXY.key.gpg
2023-08-29 23:04:41 [hasta.scilifelab.se](http://hasta.scilifelab.se/) cg.utils.commands[56113] CRITICAL Call ['/bin/gpg', '--decrypt', '--batch', '--cipher-algo', <CipherAlgorithm.AES256: 'AES256'>, '--passphrase', <EncryptionUserID.HASTA_USER_ID: 'Clinical Genomics'>, '-o', '/home/proj/production/flow_cells/210115_A00689_0215_BHKK23DSXY.key', '/home/proj/production/flow_cells/210115_A00689_0215_BHKK23DSXY.key.gpg'] exit with a non zero exit code
2023-08-29 23:04:41 [hasta.scilifelab.se](http://hasta.scilifelab.se/) cg.utils.commands[56113] CRITICAL gpg: encrypted with 2048-bit RSA key, ID 39E1F18E, created 2016-03-10
```

The key seems to be retrieved but it can't proceed after that. Might have something to do with the change in the flow cell runs directory.

**Comment by ChrOertlin** [comment]
@henrikstranneheim I think you spent some time on the PDC retrieval, right? Was this resolved?

**Comment by Vince-janv** [comment]
This has been solved here: https://github.com/Clinical-Genomics/cg/pull/2638
The whole module is still a bit shaky though
