### ISSUE TITLE
Missing sample project during parsing of demultiplexed flow cells with a flat output structure

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/cg#2247]
## Description
When running the new post processing command for a flow cell with a flat output structure demultiplexed with bcl convert the following error occurs:

```shell
 cg demultiplex finish temporary 20230508_LH00188_0003_A22522YLT3
Running cg demultiplex.
Instantiating cgstats api
Set environment to stage
Finish flow cell 20230508_LH00188_0003_A22522YLT3,
Flow cell already exists in status db: 22522YLT3. Skipping.
Parsing BCLConvert metrics file: /home/proj/stage/demultiplexed-runs/20230508_LH00188_0003_A22522YLT3/Reports/Quality_Metrics.csv
Parsing BCLConvert metrics file: /home/proj/stage/demultiplexed-runs/20230508_LH00188_0003_A22522YLT3/Reports/Demultiplex_Stats.csv
Failed to store flow cell data: 1 validation error for BclConvertDemuxMetrics
Sample_Project
  field required (type=value_error.missing)
Traceback (most recent call last):
  File "/home/proj/stage/bin/miniconda3/envs/S_main/bin/cg", line 8, in <module>
    sys.exit(base())
  File "/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/cg/cli/demultiplex/finish.py", line 65, in finish_flow_cell_temporary
    flow_cell_directory_name=flow_cell_directory_name
  File "/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/cg/meta/demultiplex/demux_post_processing.py", line 111, in finish_flow_cell_temp
    self.store_flow_cell_data(parsed_flow_cell)
  File "/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/cg/meta/demultiplex/demux_post_processing.py", line 121, in store_flow_cell_data
    self.store_sequencing_metrics_in_status_db(parsed_flow_cell)
  File "/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/cg/meta/demultiplex/demux_post_processing.py", line 130, in store_sequencing_metrics_in_status_db
    bcl_converter=flow_cell.bcl_converter,
  File "/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/cg/apps/sequencing_metrics_parser/api.py", line 19, in create_sample_lane_sequencing_metrics_for_flow_cell
    flow_cell_dir=flow_cell_directory
  File "/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/cg/apps/sequencing_metrics_parser/parsers/bcl_convert_to_sequencing_statistics.py", line 15, in create_sample_lane_sequencing_metrics_from_bcl_convert_metrics_for_flow_cell
    bcl_convert_metrics_dir_path=flow_cell_dir,
  File "/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/cg/apps/sequencing_metrics_parser/parsers/bcl_convert.py", line 53, in __init__
    metrics_model=BclConvertDemuxMetrics,
  File "/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/cg/apps/sequencing_metrics_parser/parsers/bcl_convert.py", line 77, in parse_metrics_file
    parsed_metrics.append(metrics_model(**sample_metrics_dict))
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for BclConvertDemuxMetrics
Sample_Project
  field required (type=value_error.missing)
```

## Suggested solution
It seems like the Sample_Project property is not used anywhere in the code base, so we can most likely just skip parsing it.

## This can be closed when
`cg demultiplex finish temporary 20230508_LH00188_0003_A22522YLT3` is able to parse the flow cell without throwing an error like above.

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by ChrOertlin** [comment]
This issue has been addressed in: https://github.com/Clinical-Genomics/cg/pull/2248/
