### ISSUE TITLE
Make sure the flow cell retrieved from PDC is the latest version

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/cg#2396]
## Description
A few flow cells have been backed up multiple times. However when we fetch them from PDC we do not ensure that it we are fetching the latest version.

Related module: `cg/meta/backup/pdc.py`

Bug report: https://github.com/Clinical-Genomics/bug-reports/issues/5

**Comment by Vince-janv** [comment]
Flow cells to test on: `HKCGYDSX7` or `HK5W3CCXX`

**Comment by henrikstranneheim** [comment]
@diitaz93 @Vince-janv @karlnyr Still an issue?

**Comment by Vince-janv** [comment]
> @diitaz93 @Vince-janv @karlnyr Still an issue?

Yes, but not urgent at all IMO

**Comment by Vince-janv** [comment]
## Technical refinement
- Change `dsmc_q_archive_output` be the output in the bug-report
- Make sure the pytest replicate the bug
- Change `cg.services.illumina.backup.backup_service.IlluminaBackupService.get_archived_encryption_key_path` to always return the latest key
- Change `cg.services.illumina.backup.backup_service.IlluminaBackupService.get_archived_sequencing_run_path` to take always return the latest key

**Comment by RasmusBurge-CG** [comment]
After meeting with VJ

## Step 1

- [ ] Create a new fixture that reproduces the issue where more than one file and key is encountered (make sure to anonymize any sensitive fields).
- [ ] Patch the current tests to work with the new fixture.
- [ ] Write a new test that checks whether the latest file and key are returned. This test should initially fail, and after completing Step 2, it should pass.

## Step 2

- [ ] Develop a new utility that compares date and time from a given list and returns the most recent timestamp. Implement this in: `cg.services.illumina.backup.backup_service.IlluminaBackupService.get_archived_encryption_key_path` and   `cg.services.illumina.backup.backup_service.IlluminaBackupService.get_archived_sequencing_run_path`
- [ ] Verify that the new test now passes.

## Bonus points

- [ ] Refactor to remove magic indexes in an efficient and maintainable way.

**Comment by RasmusBurge-CG** [comment]
This one is ready for review :)

**Comment by RasmusBurge-CG** [comment]
Pull request I very much done and approved. 

I will now try to test if my changes work.

I will first try to see what I will get with the current master and then switch to see if the changes were correct. 

- [ ] Test master
- [ ] Test branch
- [ ] Get approval from colleague

**Comment by RasmusBurge-CG** [comment]
Hi @Vince-janv!

Are there any unforeseen consequences of fetching a flow cell on stage? (Most things are unforeseen for me, honestly—but should I, for example, think about removing the flow cell when I’m done?)

`cg backup fetch-illumina-run -f <flowcell_id> `

**Comment by Vince-janv** [comment]
This part is seldom tested on stage so I'm not a 100% sure it works. I would try and, like you say, remove the flow cell after testing

**Comment by RasmusBurge-CG** [comment]
[15:17] [hiseq.clinical@hasta:~] [S_base]  $ cg backup fetch-illumina-run -f HKCGYDSX7 2>&1 | tee output.log
2024-10-25 15:25:07 hasta.scilifelab.se cg.meta.backup.backup[42518] INFO HKCGYDSX7: retrieving from PDC
2024-10-25 15:25:07 hasta.scilifelab.se cg.utils.commands[42518] INFO Running command /bin/dsmc q archive /home/proj/stage/encrypt/'*'/*HKCGYDSX7*.gpg
2024-10-25 15:25:11 hasta.scilifelab.se cg.utils.commands[42518] CRITICAL Call ['/bin/dsmc', 'q', 'archive', "/home/proj/stage/encrypt/'*'/*HKCGYDSX7*.gpg"] exit with a non zero exit code
2024-10-25 15:25:11 hasta.scilifelab.se cg.utils.commands[42518] CRITICAL ANS1092W No files matching search criteria were found
2024-10-25 15:25:11 hasta.scilifelab.se cg.services.pdc_service.pdc_service[42518] WARNING Command '['/bin/dsmc', 'q', 'archive', "/home/proj/stage/encrypt/'*'/*HKCGYDSX7*.gpg"]' returned non-zero exit status 8.
2024-10-25 15:25:11 hasta.scilifelab.se cg.utils.commands[42518] INFO Running command /bin/dsmc q archive /home/hiseq.clinical-stage/ENCRYPT/*HKCGYDSX7*.gpg
2024-10-25 15:25:15 hasta.scilifelab.se cg.utils.commands[42518] CRITICAL Call ['/bin/dsmc', 'q', 'archive', '/home/hiseq.clinical-stage/ENCRYPT/*HKCGYDSX7*.gpg'] exit with a non zero exit code
2024-10-25 15:25:15 hasta.scilifelab.se cg.utils.commands[42518] CRITICAL ANS1092W No files matching search criteria were found
2024-10-25 15:25:15 hasta.scilifelab.se cg.services.pdc_service.pdc_service[42518] WARNING Command '['/bin/dsmc', 'q', 'archive', '/home/hiseq.clinical-stage/ENCRYPT/*HKCGYDSX7*.gpg']' returned non-zero exit status 8.
2024-10-25 15:25:15 hasta.scilifelab.se cg.utils.commands[42518] INFO Running command /bin/dsmc q archive /mnt/hds/proj/bioinfo-stage/TO_PDC/*HKCGYDSX7*.gpg
2024-10-25 15:25:19 hasta.scilifelab.se cg.utils.commands[42518] CRITICAL Call ['/bin/dsmc', 'q', 'archive', '/mnt/hds/proj/bioinfo-stage/TO_PDC/*HKCGYDSX7*.gpg'] exit with a non zero exit code
2024-10-25 15:25:19 hasta.scilifelab.se cg.utils.commands[42518] CRITICAL ANS1092W No files matching search criteria were found
2024-10-25 15:25:19 hasta.scilifelab.se cg.services.pdc_service.pdc_service[42518] WARNING Command '['/bin/dsmc', 'q', 'archive', '/mnt/hds/proj/bioinfo-stage/TO_PDC/*HKCGYDSX7*.gpg']' returned non-zero exit status 8.
Traceback (most recent call last):
  File "/home/proj/stage/bin/miniconda3/envs/S_cg/bin/cg", line 8, in <module>
    sys.exit(base())
             ^^^^^^
  File "/home/proj/stage/bin/miniconda3/envs/S_cg/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/stage/bin/miniconda3/envs/S_cg/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/proj/stage/bin/miniconda3/envs/S_cg/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/stage/bin/miniconda3/envs/S_cg/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/stage/bin/miniconda3/envs/S_cg/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/stage/bin/miniconda3/envs/S_cg/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/stage/bin/miniconda3/envs/S_cg/lib/python3.11/site-packages/click/decorators.py", line 45, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/stage/bin/miniconda3/envs/S_cg/lib/python3.11/site-packages/cg/cli/backup.py", line 170, in fetch_illumina_run
    retrieval_time: float | None = backup_api.fetch_sequencing_run(sequencing_run)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/stage/bin/miniconda3/envs/S_cg/lib/python3.11/site-packages/cg/services/illumina/backup/backup_service.py", line 95, in fetch_sequencing_run
    dsmc_output: list[str] = self.query_pdc_for_sequencing_run(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/stage/bin/miniconda3/envs/S_cg/lib/python3.11/site-packages/cg/services/illumina/backup/backup_service.py", line 269, in query_pdc_for_sequencing_run
    raise PdcNoFilesMatchingSearchError(
cg.exc.PdcNoFilesMatchingSearchError: No flow cell files found at PDC for HKCGYDSX7

**Comment by RasmusBurge-CG** [comment]
Running it again:
```
[15:26] [hiseq.clinical@hasta:~] [S_base]  $ cg backup fetch-illumina-run -f HKCGYDSX7
Processing queue is full
<cg.store.models.IlluminaSequencingRun object at 0x7f38ac491810>: updating sequencing run data availability to requested
```

**Comment by RasmusBurge-CG** [comment]
Tested on stage and the latest file was found. ✅

**Comment by RasmusBurge-CG** [comment]
Tested senario with only one sequence run (the normal case) and it passed. ✅
Also, tested that I got an error when faulty FC was given, that also passed. ✅

**Comment by RasmusBurge-CG** [comment]
tested using `dsmc q archive <path>/*<FLOW_CELL> *.gpg`
