### ISSUE TITLE
cg backup retrieve CLI command not working

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/cg#2472]
## Description

The command to retrieve a flow cell from PDC (`cg backup retrieve`) is not working.

Currently the command runs three big processes sequentially.

- A dsmc command which fetches 1 flow cell and its key from PDC.
- A gpg command to decrypt the retrieved flow cell. 
- A tar command do decompress the archive into flow_cells
- It then touches an RTAComplete.txt file to mark that the process is complete

Each of the first three processes take several hours to complete. 

Unfortunately the errors thrown are terribly uninformative:

```
INFO Running command /bin/gpg --decrypt --batch --cipher-algo AES256 --passphrase Clinical Genomics -o /home/proj/production/flow_cells/210115_A00689_0215_BHKK23DSXY.key /home/proj/production/flow_cells/210115_A00689_0215_BHKK23DSXY.key.gpg
2023-09-12 12:11:07 [hasta.scilifelab.se](http://hasta.scilifelab.se/) cg.utils.commands[193439] CRITICAL Call ['/bin/gpg', '--decrypt', '--batch', '--cipher-algo', <CipherAlgorithm.AES256: 'AES256'>, '--passphrase', <EncryptionUserID.HASTA_USER_ID: 'Clinical Genomics'>, '-o', '/home/proj/production/flow_cells/210115_A00689_0215_BHKK23DSXY.key', '/home/proj/production/flow_cells/210115_A00689_0215_BHKK23DSXY.key.gpg'] exit with a non zero exit code
2023-09-12 12:11:07 [hasta.scilifelab.se](http://hasta.scilifelab.se/) cg.utils.commands[193439] CRITICAL gpg: encrypted with 2048-bit RSA key, ID 39E1F18E, created 2016-03-10
     "Clinical Genomics (Used in PDC related encryption/decryption) <[clinicalgenomicsstockholm@gmail.com](mailto:clinicalgenomicsstockholm@gmail.com)>"
gpg: handle plaintext failed: General error
2023-09-12 12:11:07 [hasta.scilifelab.se](http://hasta.scilifelab.se/) cg.meta.backup.backup[193439] ERROR Decryption failed: None
Traceback (most recent call last):
 File "/home/proj/production/bin/miniconda3/envs/P_main/bin/cg", line 8, in <module>
   sys.exit(base())
 File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/click/core.py", line 722, in __call__
   return self.main(*args, **kwargs)
 File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/click/core.py", line 697, in main
   rv = self.invoke(ctx)
 File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
   return _process_result(sub_ctx.command.invoke(sub_ctx))
 File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
   return _process_result(sub_ctx.command.invoke(sub_ctx))
 File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/click/core.py", line 895, in invoke
   return ctx.invoke(self.callback, **ctx.params)
 File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
   return callback(*args, **kwargs)
 File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 27, in new_func
   return f(get_current_context().obj, *args, **kwargs)
 File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/cg/cli/backup.py", line 63, in fetch_flow_cell
   retrieval_time: Optional[float] = backup_api.fetch_flow_cell(flow_cell=flow_cell)
 File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/cg/meta/backup/backup.py", line 102, in fetch_flow_cell
   archived_flow_cell=archived_flow_cell,
 File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/cg/meta/backup/backup.py", line 134, in _process_flow_cell
   raise error
 File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/cg/meta/backup/backup.py", line 122, in _process_flow_cell
   ) = self.decrypt_flow_cell(archived_flow_cell, archived_key, run_dir)
 File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/cg/meta/backup/backup.py", line 192, in decrypt_flow_cell
   self.encryption_api.run_gpg_command(decryption_command)
 File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/cg/meta/encryption/encryption.py", line 30, in run_gpg_command
   self.process.run_command(command, dry_run=self.dry_run)
 File "/home/proj/production/bin/miniconda3/envs/P_main/lib/python3.7/site-packages/cg/utils/commands.py", line 107, in run_command
   raise CalledProcessError(res.returncode, command)
subprocess.CalledProcessError: Command '['/bin/gpg', '--decrypt', '--batch', '--cipher-algo', <CipherAlgorithm.AES256: 'AES256'>, '--passphrase', <EncryptionUserID.HASTA_USER_ID: 'Clinical Genomics'>, '-o', '/home/proj/production/flow_cells/210115_A00689_0215_BHKK23DSXY.key', '/home/proj/production/flow_cells/210115_A00689_0215_BHKK23DSXY.key.gpg']' returned non-zero exit status 2.
```

### Manual solution
For all flow cells i have encountered it seems like the decryption has succeeded but since the command is run sequentially, it restarts with dsmc and then gpg, and fails again. The steps I take manually to fix a flow cell are described [here](https://github.com/Clinical-Genomics/cg/issues/2114#issuecomment-1653099305).

## Suggested solution
- [ ] Improve logging for the gpg command to find out why its crashing or at least reports that it is crashing
- [ ] Separate the three big commands
- [ ] Instead of running the commands on the hasta login node, queue them to SLURM

## This can be closed when

The `cg backup retrieve` CLI command reliably fetches, decrypts and decompresses flow cells needed in production

**Comment by Vince-janv** [comment]
### Questions to answer regarding the suggested solution:
- How to know where a flow cell is in the process?
    - Check files and timestamps?
    - Extend the status column in the flow cell table?
- If we want to use SLURM, we need to install dsmc on at least one, ideally two nodes. Do we want this?

**Comment by Vince-janv** [comment]
## Topic was discussed partly but postponed due to lack of time
### Agreed points:
- Divide the command into three separate steps.
- Send the steps to SLURM for execution.

### Remaining questions:
- How do we handle the automation of a three step process

### Suggested solution
- Create three CLI commands.
    - Fetch flow cell
        - Triggered by timer
        - Takes the flow cell that has been requested for longest
        - Submits a SLURM job with the dsmc command to fetch the flow cell.
    - Decrypt flow cell
         - Triggered by file watcher (watch for .gpg files)
         - Takes the .gpg file with the most recent change.
         - Submits a SLURM job with the gpg command to decrypt the flow cell and removes the .gpg file upon completion.
    - Untarr flow cell
        -  Triggered by file watcher (watch for .tar files)
         - Takes the .tar file with the most recent change.
         - Submits a SLURM job with the gpg command to decrypt the flow cell and removes the .tar file upon completion
         - Sets the flow cell as ondisk
         - Touches a file to mark the flow cell as ready for demultiplexing.

**Comment by Vince-janv** [comment]
### Decision
- [ ] Ask IT about SELinux
- [ ] Try to catch error in cg-code to patch the flow
- [ ] Work on the rest of the issue in two weeks when encryption and demuxdir PR:s are merged

**Comment by ChrOertlin** [comment]
is refined, moving to ready column

**Comment by ChrOertlin** [comment]
# Refinement

Require status update on this issue @Vince-janv

**Comment by Vince-janv** [comment]
Closing as done
