### ISSUE TITLE
Error in cleaning old BAMs

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/cg#2569]
## Description

● cg-clean-scout-finished.service - Removal of BAM files from finished cases
  Loaded: loaded (/home/hiseq.clinical/.config/systemd/user/cg-clean-scout-finished.service; enabled; vendor preset: enabled)
  Active: failed (Result: exit-code) since Mon 2023-10-09 09:10:56 CEST; 15ms ago
 Process: 201383 ExecStart=/bin/bash -c /home/proj/production/bin/miniconda3/envs/P_cg/bin/cg      --config /home/proj/production/servers/config/[hasta.scilifelab.se/cg.yaml](http://hasta.scilifelab.se/cg.yaml)      clean      scout-finished-cases      -y      --days-old 300 (code=exited, status=1/FAILURE)
Main PID: 201383 (code=exited, status=1/FAILURE)

Oct 09 09:10:56 [hasta.scilifelab.se](http://hasta.scilifelab.se/) systemd[6197]: Failed to start Removal of BAM files from finished cases.
Oct 09 09:10:56 [hasta.scilifelab.se](http://hasta.scilifelab.se/) systemd[6197]: cg-clean-scout-finished.service failed.

```
cg clean scout-finished-cases -y --days-old 300
Validating case eageralpaca
Validating case casualduck
Validating case realmammal
Validating case newiguana
Validating case humbleminnow
Validating case happymoose
Validating case luckyhermit
Validating case realpup
Traceback (most recent call last):
  File "/home/proj/production/bin/miniconda3/envs/P_cg/bin/cg", line 8, in <module>
    sys.exit(base())
  File "/home/proj/production/bin/miniconda3/envs/P_cg/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/proj/production/bin/miniconda3/envs/P_cg/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/proj/production/bin/miniconda3/envs/P_cg/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/production/bin/miniconda3/envs/P_cg/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/production/bin/miniconda3/envs/P_cg/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/proj/production/bin/miniconda3/envs/P_cg/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/proj/production/bin/miniconda3/envs/P_cg/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/production/bin/miniconda3/envs/P_cg/lib/python3.8/site-packages/cg/cli/clean.py", line 126, in scout_finished_cases
    cases: List[ScoutExportCase] = scout_api.get_cases(status=status, reruns=False)
  File "/home/proj/production/bin/miniconda3/envs/P_cg/lib/python3.8/site-packages/cg/apps/scout/scoutapi.py", line 163, in get_cases
    cases.append(ScoutExportCase.model_validate(case_export))
  File "/home/proj/production/bin/miniconda3/envs/P_cg/lib/python3.8/site-packages/pydantic/main.py", line 503, in model_validate
    return cls.__pydantic_validator__.validate_python(
pydantic_core._pydantic_core.ValidationError: 2 validation errors for ScoutExportCase
individuals.0.father
  Input should be a valid string [type=string_type, input_value=0, input_type=int]
    For further information visit https://errors.pydantic.dev/2.4/v/string_type
individuals.0.mother
  Input should be a valid string [type=string_type, input_value=0, input_type=int]
    For further information visit https://errors.pydantic.dev/2.4/v/string_type
```

## This can be closed when

Cleaning works

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by henrikstranneheim** [comment]
@islean Could you take a look?

**Comment by islean** [comment]
@henrikstranneheim Sure!

**Comment by Vince-janv** [comment]
@islean can this be closed?
