### ISSUE TITLE
Order portal broken

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/cg#2572]
## Description
When placings a sars cov order
```
Oct 09 11:40:31 cg-vm1.scilifelab.se podman[217535]: [2023-10-09 11:40:31 +0200] [6] [DEBUG] Closing connection.
Oct 09 11:40:31 cg-vm1.scilifelab.se podman[217535]: 10.0.2.100 - - [09/Oct/2023:11:40:31 +0200] "POST /api/v1/submit_order/sars-cov-2 HTTP/1.0" 500 342 "https://clinical-stage.scilifelab.se/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko)>
Oct 09 11:40:31 cg-vm1.scilifelab.se podman[217535]: requests.exceptions.HTTPError: b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>503 Service Unavailable</title>\n</head><body>\n<h1>Service Unavailable</h1>\n<p>The server is temporarily unable to servic>
Oct 09 11:40:31 cg-vm1.scilifelab.se podman[217535]:     raise requests.exceptions.HTTPError(message, response=response)
Oct 09 11:40:31 cg-vm1.scilifelab.se podman[217535]:   File "/usr/local/lib/python3.8/site-packages/genologics/lims.py", line 202, in validate_response
Oct 09 11:40:31 cg-vm1.scilifelab.se podman[217535]:     self.validate_response(response, accept_status_codes)
Oct 09 11:40:31 cg-vm1.scilifelab.se podman[217535]:   File "/usr/local/lib/python3.8/site-packages/genologics/lims.py", line 209, in parse_response
Oct 09 11:40:31 cg-vm1.scilifelab.se podman[217535]:     return self.parse_response(r, accept_status_codes=[200, 201, 202])
Oct 09 11:40:31 cg-vm1.scilifelab.se podman[217535]:   File "/usr/local/lib/python3.8/site-packages/genologics/lims.py", line 158, in post
Oct 09 11:40:31 cg-vm1.scilifelab.se podman[217535]:     instance.root = lims.post(uri=lims.get_uri(cls._URI), data=data)
Oct 09 11:40:31 cg-vm1.scilifelab.se podman[217535]:   File "/usr/local/lib/python3.8/site-packages/genologics/entities.py", line 331, in create
Oct 09 11:40:31 cg-vm1.scilifelab.se podman[217535]:     lims_project = Project.create(
Oct 09 11:40:31 cg-vm1.scilifelab.se podman[217535]:   File "/home/src/app/cg/apps/lims/order.py", line 56, in submit_project
Oct 09 11:40:31 cg-vm1.scilifelab.se podman[217535]:     project_data = lims_api.submit_project(
Oct 09 11:40:31 cg-vm1.scilifelab.se podman[217535]:   File "/home/src/app/cg/meta/orders/lims.py", line 29, in process_lims
Oct 09 11:40:31 cg-vm1.scilifelab.se podman[217535]:     project_data, lims_map = process_lims(
Oct 09 11:40:31 cg-vm1.scilifelab.se podman[217535]:   File "/home/src/app/cg/meta/orders/microbial_submitter.py", line 44, in submit_order
Oct 09 11:40:31 cg-vm1.scilifelab.se podman[217535]:     return submit_handler.submit_order(order=order_in)
Oct 09 11:40:31 cg-vm1.scilifelab.se podman[217535]:   File "/home/src/app/cg/meta/orders/api.py", line 87, in submit
Oct 09 11:40:31 cg-vm1.scilifelab.se podman[217535]:     result = api.submit(
Oct 09 11:40:31 cg-vm1.scilifelab.se podman[217535]:   File "/home/src/app/cg/server/api.py", line 125, in submit_order
Oct 09 11:40:31 cg-vm1.scilifelab.se podman[217535]: Traceback (most recent call last):
```

**Comment by seallard** [comment]
Temporarily locking the genologics package to the previous version does not seem to resolve the issue.

**Comment by seallard** [comment]
Seems to have been a temporary issue in stage due to <reason here 👍 >
