### ISSUE TITLE
Not able to upload in-house project to scout

### ISSUE THREAD

**Issue by keyvanelhami** [Clinical-Genomics/cg#3]
For the following four cases:
4fam-Lucigen--300M
4fam-Lucigen--450M
7fam-Lucigen--300M
7fam-Lucigen--450M

The following error message appears when trying to run "cd add caseID". It seems like the LIMS ID cannot be found since --300M is added for the analysis:

```python
Traceback (most recent call last):
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/bin/cg", line 11, in <module>
    load_entry_point('cg==0.9.1', 'console_scripts', 'cg')()
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/lib/python2.7/site-packages/cg/commands.py", line 486, in add
    context.invoke(coverage, force=force, case_id=case_id)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/lib/python2.7/site-packages/cg/commands.py", line 307, in coverage
    sample_name=lims_sample.name,
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/lib/python2.7/site-packages/genologics/descriptors.py", line 53, in __get__
    instance.get()
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/lib/python2.7/site-packages/genologics/entities.py", line 287, in get
    self.root = self.lims.get(self.uri)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/lib/python2.7/site-packages/genologics/lims.py", line 90, in get
    return self.parse_response(r)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/lib/python2.7/site-packages/genologics/lims.py", line 196, in parse_response
    self.validate_response(response, accept_status_codes)
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/lib/python2.7/site-packages/genologics/lims.py", line 189, in validate_response
    raise requests.exceptions.HTTPError(message)
requests.exceptions.HTTPError: 404: Sample not found: RES1574A1--300M
```

**Comment by robinandeer** [comment]
I believe we resolved, this - reopen if it shows up again!
