### ISSUE TITLE
Requests against /orders fails for specific pages

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/cg#3448]
When opening the orders view in trailblazer, the request against `/orders` in cg fails with an index error for specific pages when you go forwards loading the next 20 orders with the error below.

```
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]: 10.0.2.100 - - [18/Jul/2024:16:42:18 +0200] "GET /api/v1/orders?workflow=&search=&pageSize=20>
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]: IndexError: list index out of range
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:                      ~~~~~~~~~~~~^^^
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:     threshold: int = case.samples[0].expected_reads_for_sample
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:   File "/home/src/app/cg/services/sequencing_qc_service/quality_checks/utils.py", line 62, in>
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:     return ready_made_library_case_pass_sequencing_qc(case)
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:   File "/home/src/app/cg/services/sequencing_qc_service/quality_checks/utils.py", line 22, in>
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:                ^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:     return all(quality_check(**kwargs) for quality_check in quality_checks)
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:   File "/home/src/app/cg/services/sequencing_qc_service/quality_checks/checks.py", line 61, i>
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:     return all(quality_check(**kwargs) for quality_check in quality_checks)
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:   File "/home/src/app/cg/services/sequencing_qc_service/quality_checks/checks.py", line 61, i>
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:     return run_quality_checks(quality_checks=[sequencing_quality_check], case=case)
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:   File "/home/src/app/cg/services/sequencing_qc_service/sequencing_qc_service.py", line 37, i>
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^>
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:     return case.are_all_samples_sequenced and not SequencingQCService.case_pass_sequencing_qc>
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:   File "/home/src/app/cg/services/orders/order_summary_service/utils.py", line 11, in _is_cas>
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:     if _is_case_failed_sequencing_qc(case) and case.internal_id not in cases_to_exclude
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:   File "/home/src/app/cg/services/orders/order_summary_service/utils.py", line 19, in <genexp>
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:     if _is_case_failed_sequencing_qc(case) and case.internal_id not in cases_to_exclude
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:   File "/home/src/app/cg/services/orders/order_summary_service/utils.py", line 19, in <genexp>
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:            ^^^^
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:     return sum(
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:   File "/home/src/app/cg/services/orders/order_summary_service/utils.py", line 16, in get_cas>
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:     failed_sequencing_qc: int = get_cases_failed_sequencing_qc_count(
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:   File "/home/src/app/cg/services/orders/order_summary_service/order_summary_service.py", lin>
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:     order_summary = self.create_order_summary(order=order, summary=analysis_summary)
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:   File "/home/src/app/cg/services/orders/order_summary_service/order_summary_service.py", lin>
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:     order_summaries = self.create_summaries(orders=orders, analysis_summaries=analyses)
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:   File "/home/src/app/cg/services/orders/order_summary_service/order_summary_service.py", lin>
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:     summaries: list[OrderSummary] = self.summary_service.get_summaries(order_ids)
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:   File "/home/src/app/cg/services/orders/order_service/order_service.py", line 33, in get_ord>
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:     response: OrdersResponse = order_service.get_orders(data)
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:   File "/home/src/app/cg/server/api.py", line 491, in get_orders
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:          ^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:     rv = self.dispatch_request()
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_req>
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:                                                 ^^^^^^^^^^^^^^^^^^
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:     return cors_after_request(app.make_response(f(*args, **kwargs)))
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:   File "/usr/local/lib/python3.11/site-packages/flask_cors/extension.py", line 178, in wrappe>
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:     rv = self.handle_user_exception(e)
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_req>
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:     response = self.full_dispatch_request()
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]:   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
Jul 18 16:42:18 cg-services-prod.scilifelab.se podman[1969762]: Traceback (most recent call last):
```

**Comment by seallard** [comment]
> Could this be behind this issue I have noticed? [Clinical-Genomics/cigrid-ui#664](https://github.com/Clinical-Genomics/cigrid-ui/issues/664)

Maybe 👍

**Comment by seallard** [comment]
The bug is due to the sequencing qc logic being run in the `orders` endpoint which does not filter away cases without samples. We are currently removing that logic from the endpoint entirely and this issue will be resolved.

Closed as this issue is tracking the root cause https://github.com/Clinical-Genomics/cg/issues/3223

Prioritizing this now.

**Comment by seallard** [comment]
Resolved in https://github.com/Clinical-Genomics/cg/pull/3403#event-13597614926
