### ISSUE TITLE
Bug: deliver files service unable to deliver case has no files

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/cg#3712]
**Describe the bug**

When a user runs the command `cg deliver ticket -d <delivery_type> -t <ticket_id>` on a ticket where not all cases have files, the code exits. I see this as a bug, as I believe the idea is that the delivery service should not fail if there are missing files, but instead, it should return information to the user that there are no files, without throwing errors. The same applies when the user runs `cg deliver case`. As we are unable to deliver tickets currently, due to missing data, and no ability to force the delivery, I see this as a bug, rather than a feature request.

Error log is the same for both commands, so I will paste it below:

```Command
[09:36] [hiseq.clinical@hasta:~] [P_base]  $ cg deliver case -d fastq -c toughparrot
Running CG deliver
Called undefined __fields__ on HousekeeperAPI, please wrap
Bundle: ACC14956A8DS80C0M not found in Housekeeper

Traceback (most recent call last):
  File "/home/proj/production/bin/miniconda3/envs/P_cg/bin/cg", line 8, in <module>
    sys.exit(base())
             ^^^^^^
  File "/home/proj/production/bin/miniconda3/envs/P_cg/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/production/bin/miniconda3/envs/P_cg/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/proj/production/bin/miniconda3/envs/P_cg/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/production/bin/miniconda3/envs/P_cg/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/production/bin/miniconda3/envs/P_cg/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/production/bin/miniconda3/envs/P_cg/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/production/bin/miniconda3/envs/P_cg/lib/python3.11/site-packages/click/decorators.py", line 45, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/production/bin/miniconda3/envs/P_cg/lib/python3.11/site-packages/cg/cli/deliver/base.py", line 96, in deliver_case
    delivery_service.deliver_files_for_case(
  File "/home/proj/production/bin/miniconda3/envs/P_cg/lib/python3.11/site-packages/cg/services/deliver_files/deliver_files_service/deliver_files_service.py", line 68, in deliver_files_for_case
    formatted_files: FormattedFiles = self.file_formatter.format_files(moved_files)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/production/bin/miniconda3/envs/P_cg/lib/python3.11/site-packages/cg/services/deliver_files/delivery_file_formatter_service/delivery_file_formatter.py", line 46, in format_files
    delivery_files.sample_files[0].file_path
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**To Reproduce**
Steps to reproduce the behaviour:
1. `up`
1. `cg deliver ticket -d fastq -t 272868`
1. or `cg deliver case -d fastq -c toughparrot`

**Expected behaviour**

When I run `cg deliver ticket`, or `cg deliver case`, on a case(s) missing files to deliver I would expect the service to not try to move said files. 

When I run `cg deliver case` on a case missing data, the service should report back what files it could not deliver, followed by either raising an error or exiting the command. 

When I run `cg deliver ticket` on a ticket where cases may be missing data, I want the service to deliver the data that is currently available, report back which files were missing for a case, and continue to the next one.

**Comment by karlnyr** [comment]
### Discussion

On meeting, we found that we should better inform the use for `cg deliver case` that:

- Give us more information when `cg deliver case` is run
   - where case files missing, which ones
   - where sample files missing, which ones

For `cg deliver ticket` we are however split:

1. Add `--force-flag` if you would want to deliver everything available for a ticket (the flag could be renamed, but the logic would be the same)
2. To just deliver all cases by default, collect information on what case/sample files were missing and report at the end of the command
3. Confirmation message, asking the user if they would like to deliver all data anyway

**Comment by ChrOertlin** [comment]
@karlnyr 

These two points:

> * Give us more information when `cg deliver case` is run
>   
>   * where case files missing, which ones
>   * where sample files missing, which ones

Is it enough to give back case_id and file tags for missing files? Giving back file names is kind of hard without creating a reference that contains the expected files for each workflow. I don't think that is feasible or maintainable.

Would be something like: _"File with tags X.y.z missing for case / sample in housekeeper."_

**Comment by ChrOertlin** [comment]
Now looking at the code. it would just give all sample tags in its current form. Best one can do without some larger effort is to report the bundle name if it is missing.

**Comment by ChrOertlin** [comment]
fixed
