### ISSUE TITLE
cg analysis link fails on missing link or error does not provide a clear explanation what the problem is

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#395]
Problem: 
`cg analysis link -f family_id` fails without proper explanation if link does not exist.

Example: if there are three samples in one family, and first one doesn't have fast files linked OR the sequence files are not ready due to various reasons (I'll explain below), the files don't link. I can't provide any example without giving away LIMS ids on public location.

Reasons on why fastq might not exist:
- Not sequenced.
- Sample might be RNA but we don't have RNA set yet (Maybe?)
- That particular sample is linked by mistake to the family. The sample does not and will not have any fastqs linked to it.

Steps to reproduce
  1. run cg analysis link -f on a family where one sample has zero read or no fastq files.

Expected outcome / suggested solution:
Skip that sample _AND_ provide a proper message why linking failed.

Questions: 
Q: Does the same problem occur for tea?
A: Yes.

What needs to be done on the planning meeting:
- Estimate storypoints
- **Remember to add label *PBL Teamname***

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by hassanfa** [comment]
An example of current error:
```
Traceback (most recent call last):
  File "/home/proj/bin/conda/envs/P_main/bin/cg", line 11, in <module>
    sys.exit(base())
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/analysis.py", line 124, in link
    sample=link_obj.sample.internal_id)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/meta/analysis.py", line 236, in link_sample
    fastq_handler.link(case=case, sample=sample, files=files)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/apps/balsamic/fastq.py", line 144, in link
    concatenated_paths[read])
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/apps/balsamic/fastq.py", line 29, in concatenate
    with open(concat_file, 'wb') as wfd:
FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Comment by ingkebil** [comment]
Do you have an example of a family?

**Comment by hassanfa** [comment]
Examples are here: https://github.com/Clinical-Genomics/Cancer-project/issues/30

All four families.

**Comment by hassanfa** [comment]
Emilia and I removed badly linked families (from OF) for one of them. I don't recall which one. I can check if you want.

**Comment by Mropat** [comment]
This is outdated
