### ISSUE TITLE
Fail to link fastq-file with cg

### ISSUE THREAD

**Issue by keyvanelhami** [Clinical-Genomics/cg#424]
As a busy person, I want to drink coffee so that I wake up.

Problem: 
Fail to link fastq-file for sample ACC5810A53 in family stablemolly. There are in total ≈50 samples in this family. 

Steps to reproduce
1) `cg analysis link -f stablemolly`
2) The scripts fails when trying to link ACC5810A53:
`Concatenating: 1_171015_HLYVJDSXX_ACC5810A52_XXXXXX_R_1.fastq.gz, 2_171015_HLYVJDSXX_ACC5810A52_XXXXXX_R_1.fastq.gz, 3_171015_HLYVJDSXX_ACC5810A52_XXXXXX_R_1.fastq.gz, 4_171015_HLYVJDSXX_ACC5810A52_XXXXXX_R_1.fastq.gz -> concatenated_ACC5810A52_XXXXXX_R_1.fastq.gz
Concatenation file size check successful!
Concatenating: 1_171015_HLYVJDSXX_ACC5810A52_XXXXXX_R_2.fastq.gz, 2_171015_HLYVJDSXX_ACC5810A52_XXXXXX_R_2.fastq.gz, 3_171015_HLYVJDSXX_ACC5810A52_XXXXXX_R_2.fastq.gz, 4_171015_HLYVJDSXX_ACC5810A52_XXXXXX_R_2.fastq.gz -> concatenated_ACC5810A52_XXXXXX_R_2.fastq.gz
Concatenation file size check successful!
ACC5810A53: link FASTQ files
Concatenation in progress for sample ACC5810A53.
Concatenating:  -> 
Traceback (most recent call last):
  File "/home/proj/bin/conda/envs/P_main/bin/cg", line 11, in <module>
    sys.exit(base())
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/analysis.py", line 124, in link
    sample=link_obj.sample.internal_id)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/meta/analysis.py", line 236, in link_sample
    fastq_handler.link(case=case, sample=sample, files=files)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/apps/balsamic/fastq.py", line 144, in link
    concatenated_paths[read])
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/apps/balsamic/fastq.py", line 29, in concatenate
    with open(concat_file, 'wb') as wfd:
FileNotFoundError: [Errno 2] No such file or directory: ''
`

Expected outcome / suggested solution:
All samples to be linked

Questions: 
-

What needs to be done on the planning meeting:

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by keyvanelhami** [comment]
Problem solved:
Sample ACC5810A53 has simply not be sequenced :)
