### ISSUE TITLE
Permission denied linking balsamic case and exit code 1

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#452]
Running samples that have RNA that is not supposed to go through BALSAMIC return permission denied error and exit code 1 which breaks downstream scripts.

Reminder: If it is tumor RNA, it should also be marked as BALSAMIC in statusdb as well to run it through balsamic for somatic fusions.

example: `cg analysis link -f setkoi`

Error:
```
ACC5821A3: MIP link FASTQ files
Traceback (most recent call last):
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/pathlib.py", line 1241, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/home/proj/production/rare-disease/cases/setkoi/wts/ACC5821A3/fastq'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/proj/bin/conda/envs/P_main/bin/cg", line 11, in <module>
    sys.exit(base())
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/analysis.py", line 138, in link
    sample=link_obj.sample.internal_id)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/meta/analysis.py", line 237, in link_sample
    fastq_handler.link(case=case, sample=sample, files=files)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/apps/mip/fastq.py", line 38, in link
    files=files,
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/trailblazer/mip/fastq.py", line 24, in link
    root_dir.mkdir(parents=True, exist_ok=True)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/pathlib.py", line 1250, in mkdir
    if not exist_ok or not self.is_dir():
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/pathlib.py", line 1341, in is_dir
    return S_ISDIR(self.stat().st_mode)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/pathlib.py", line 1151, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/home/proj/production/rare-disease/cases/setkoi/wts/ACC5821A3/fastq'
```

**Comment by ingkebil** [comment]
What user tried to link these files?

**Comment by hassanfa** [comment]
That'd be me.

**Comment by emiliaol** [comment]
I had no idea the RNA samples should link to the cancer directory as well. Cool, so you run RNA analysis through balsamic as well? Anything that balsamic needs to know in the config (thinking of the cg config creation)?

**Comment by ingkebil** [comment]
In any case, this is a feature, not a bug. You're not in the hasta rare
disease group.

**Comment by hassanfa** [comment]
I didn't say it is a bug :-). The output of linking is not explaining the situation and log is not clear enough. If I don't have permission to link, should it exit with 1 and break my script? probably not.

Anyhow, @emiliaol it is fusioncatcher. RNASeq fastq files should suffice. Of course if they are from tumor sample. Normal will still go to mip i suppose?
