### ISSUE TITLE
PAN cases missing SV files can be uploaded to Scout using `cg upload scout`

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/cg#505]
As a prod bioinfo person I want cases analysed with MIP containing panel samples to be uploaded to Scout without any error, so that the automatic upload can handle these cases and I don't have to use time to do it manually

Problem: 
There is too little data in the panel samples to produce some files in MIP such as the SV files, and some peddy files. This leads to a problem when `cg upload scout` is supposed to create the scout load config because cg expects these files to exist. See below for example of error output from cg when trying to create the load config:

```
----------------- SCOUT -----------------------
/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/orm/query.py:2334: SAWarning: Pathed join target File.version has already been joined to; skipping
  "been joined to; skipping" % prop
Traceback (most recent call last):
  File "/home/proj/bin/conda/envs/P_main/bin/cg", line 11, in <module>
    sys.exit(base())
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/upload.py", line 112, in upload
    context.invoke(scout, case_id=family_id)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/upload.py", line 432, in scout
    scout_config = scout_upload_api.generate_config(family_obj.analyses[0])
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/meta/upload/scoutapi.py", line 68, in generate_config
    self._include_mandatory_files(data, hk_version)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/meta/upload/scoutapi.py", line 125, in _include_mandatory_files
    self._include_files(data, hk_version, scout_hk_map, skip_missing=False)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/meta/upload/scoutapi.py", line 142, in _include_files
    raise FileNotFoundError(f"missing file: {scout_key}")
FileNotFoundError: missing file: vcf_sv_research
```

Expected outcome / suggested solution:
`cg upload scout` for cases containing PA* samples (based on apptag) can create the scout load config even when some files are missing in housekeeper.
 
Questions: 
Q: 
A: 

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by Mropat** [comment]
@henrikstranneheim does this need to be fixed?

**Comment by henrikstranneheim** [comment]
This is currently solved by ordering these samples with exome sequencing instead. We will not fix this in MIP and it is currently not planned for nf-core/raredisease. Closing
