### ISSUE TITLE
Unable to start BALSAMIC-wgs analysis

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/cg#566]
A production team member should be able to start balsamic-wgs analysis.

Problem: 
In Balsamic, this is done by not providing a `--target-bed` file, which toggles WGS mode. As of now, it seems it is mandatory to provide a `--target-bed` file: https://github.com/Clinical-Genomics/cg/blob/master/cg/cli/workflow/balsamic/base.py#L231

Steps to reproduce
  1. up or us
  2. cg workflow balsamic -c eagerserval -e han.velsing@alucard.nomnom

```
Traceback (most recent call last):
  File "/home/proj/bin/conda/envs/P_main/bin/cg", line 11, in <module>
    sys.exit(base())
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/workflow/balsamic/base.py", line 75, in balsamic
    context.invoke(config_case, case_id=case_id, target_bed=target_bed)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/workflow/balsamic/base.py", line 239, in config_case
    raise BalsamicStartError("No target bed specified!")
cg.exc.BalsamicStartError
```

Expected outcome / suggested solution:
A coffee in my cup.

Questions: 
Q: Does the same problem occur for tea?
A: Yes.

What needs to be done on the planning meeting:
- Estimate storypoints
- **Remember to add label *PBL Teamname***

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by hassanfa** [comment]
WiP. Adding notes here for myself:

**Comment by keyvanelhami** [comment]
I was trying to start WGS with Balsamic on Hasta, but it seems like cg is still on the old version 7.7.2 and not 7.7.3 

`[14|2464|2694] 4d [hiseq.clinical@hasta:~] [P_main] $ cg workflow balsamic -c eagerserval -e keyvan.elhami@scilifelab.se
link all samples in a case
ACC6472A22: Balsamic link FASTQ files
ACC6472A22 has balsamic as data analysis, linking.
linking: /home/proj/production/demultiplexed-runs/200109_A00689_0093_BHYGYKDSXX/Unaligned-Y151I10I10Y151/Project_111948/Sample_ACC6472A22/HYGYKDSXX_111948_S166_L001_R1_001.fastq.gz -> /home/proj/production/cancer/cases/eagerserval/fastq/1_171015_HYGYKDSXX_ACC6472A22_XXXXXX_R_1.fastq.gz
linking: /home/proj/production/demultiplexed-runs/200109_A00689_0093_BHYGYKDSXX/Unaligned-Y151I10I10Y151/Project_111948/Sample_ACC6472A22/HYGYKDSXX_111948_S166_L001_R2_001.fastq.gz -> /home/proj/production/cancer/cases/eagerserval/fastq/1_171015_HYGYKDSXX_ACC6472A22_XXXXXX_R_2.fastq.gz
linking: /home/proj/production/demultiplexed-runs/200109_A00689_0093_BHYGYKDSXX/Unaligned-Y151I10I10Y151/Project_111948/Sample_ACC6472A22/HYGYKDSXX_111948_S166_L002_R1_001.fastq.gz -> /home/proj/production/cancer/cases/eagerserval/fastq/2_171015_HYGYKDSXX_ACC6472A22_XXXXXX_R_1.fastq.gz
linking: /home/proj/production/demultiplexed-runs/200109_A00689_0093_BHYGYKDSXX/Unaligned-Y151I10I10Y151/Project_111948/Sample_ACC6472A22/HYGYKDSXX_111948_S166_L002_R2_001.fastq.gz -> /home/proj/production/cancer/cases/eagerserval/fastq/2_171015_HYGYKDSXX_ACC6472A22_XXXXXX_R_2.fastq.gz
linking: /home/proj/production/demultiplexed-runs/200109_A00689_0093_BHYGYKDSXX/Unaligned-Y151I10I10Y151/Project_111948/Sample_ACC6472A22/HYGYKDSXX_111948_S166_L003_R1_001.fastq.gz -> /home/proj/production/cancer/cases/eagerserval/fastq/3_171015_HYGYKDSXX_ACC6472A22_XXXXXX_R_1.fastq.gz
linking: /home/proj/production/demultiplexed-runs/200109_A00689_0093_BHYGYKDSXX/Unaligned-Y151I10I10Y151/Project_111948/Sample_ACC6472A22/HYGYKDSXX_111948_S166_L003_R2_001.fastq.gz -> /home/proj/production/cancer/cases/eagerserval/fastq/3_171015_HYGYKDSXX_ACC6472A22_XXXXXX_R_2.fastq.gz
linking: /home/proj/production/demultiplexed-runs/200109_A00689_0093_BHYGYKDSXX/Unaligned-Y151I10I10Y151/Project_111948/Sample_ACC6472A22/HYGYKDSXX_111948_S166_L004_R1_001.fastq.gz -> /home/proj/production/cancer/cases/eagerserval/fastq/4_171015_HYGYKDSXX_ACC6472A22_XXXXXX_R_1.fastq.gz
linking: /home/proj/production/demultiplexed-runs/200109_A00689_0093_BHYGYKDSXX/Unaligned-Y151I10I10Y151/Project_111948/Sample_ACC6472A22/HYGYKDSXX_111948_S166_L004_R2_001.fastq.gz -> /home/proj/production/cancer/cases/eagerserval/fastq/4_171015_HYGYKDSXX_ACC6472A22_XXXXXX_R_2.fastq.gz
Concatenation in progress for sample ACC6472A22.
Concatenating: 1_171015_HYGYKDSXX_ACC6472A22_XXXXXX_R_1.fastq.gz, 2_171015_HYGYKDSXX_ACC6472A22_XXXXXX_R_1.fastq.gz, 3_171015_HYGYKDSXX_ACC6472A22_XXXXXX_R_1.fastq.gz, 4_171015_HYGYKDSXX_ACC6472A22_XXXXXX_R_1.fastq.gz -> concatenated_ACC6472A22_XXXXXX_R_1.fastq.gz
Concatenation file size check successful!
Concatenating: 1_171015_HYGYKDSXX_ACC6472A22_XXXXXX_R_2.fastq.gz, 2_171015_HYGYKDSXX_ACC6472A22_XXXXXX_R_2.fastq.gz, 3_171015_HYGYKDSXX_ACC6472A22_XXXXXX_R_2.fastq.gz, 4_171015_HYGYKDSXX_ACC6472A22_XXXXXX_R_2.fastq.gz -> concatenated_ACC6472A22_XXXXXX_R_2.fastq.gz
Concatenation file size check successful!
ACC6472A22: config FASTQ file
Traceback (most recent call last):
  File "/home/proj/bin/conda/envs/P_main/bin/cg", line 11, in <module>
    sys.exit(base())
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/workflow/balsamic/base.py", line 75, in balsamic
    context.invoke(config_case, case_id=case_id, target_bed=target_bed)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/workflow/balsamic/base.py", line 243, in config_case
    raise BalsamicStartError("No target bed specified!")
cg.exc.BalsamicStartError`

`[14|2463|2693] 4d [hiseq.clinical@hasta:~] [P_main] 54s 1 $ cg --version
cg, version 7.7.2`

**Comment by patrikgrenfeldt** [comment]
Hi @keyvanelhami, I forgot to deploy this yesterday, sorry for that. It is deployed now though
