### ISSUE TITLE
Unable to start Balsamic workflow with cg (panel)

### ISSUE THREAD

**Issue by keyvanelhami** [Clinical-Genomics/cg#586]
As a production person, I want to be able to start balsamic cases

Problem: 
Below error message occur when I try to run below script. I couldn't really understand the error message.

This error happens for all cases in `/home/proj/production/cancer/cases/github_issue_analysis/issue_50/sample_list`

`[7|305|1784] [keyvan.elhami@hasta: … on/cancer/cases] [P_main] 130 $ cg workflow balsamic --target-bed /home/proj/production/cancer/reference/panel/gmcksolid_4.1_hg19_design.bed -c idealgoblin -e keyvan.elhami@scilifelab.se`

`
link all samples in a case
ACC6516A1: Balsamic  link FASTQ files
ACC6516A1 has balsamic as data analysis, linking.
Concatenation in progress for sample ACC6516A1.
Concatenating:  -> 
Traceback (most recent call last):
  File "/home/proj/bin/conda/envs/P_main/bin/cg", line 11, in <module>
    sys.exit(base())
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/workflow/balsamic/base.py", line 74, in balsamic
    context.invoke(link, case_id=case_id)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/workflow/balsamic/base.py", line 107, in link
    sample=link_obj.sample.internal_id,
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/meta/workflow/balsamic.py", line 266, in link_sample
    fastq_handler.link(case=case, sample=sample, files=files)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/apps/balsamic/fastq.py", line 149, in link
    linked_reads_paths[read], concatenated_paths[read]
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/apps/balsamic/fastq.py", line 29, in concatenate
    with open(concat_file, "wb") as wfd:
FileNotFoundError: [Errno 2] No such file or directory: ''`

Steps to reproduce
  1. `up`
  2.  `[7|305|1784] [keyvan.elhami@hasta: … on/cancer/cases] [P_main] 130 $ cg workflow balsamic --target-bed /home/proj/production/cancer/reference/panel/gmcksolid_4.1_hg19_design.bed -c idealgoblin -e keyvan.elhami@scilifelab.se`

Expected outcome / suggested solution:
Analysis should start

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by keyvanelhami** [comment]
Sample not sequenced, that's why :)
