### ISSUE TITLE
Scout delivery for cancer

### ISSUE THREAD

**Issue by annaengstrom** [Clinical-Genomics/cg#631]
Develop Scout for cancer ready for delivery to customers

Define MVP and implement required features

**Comment by hassanfa** [comment]
The following checklist might be useful:

- [ ] Create Scout config
  - [ ] Identify bam/cram files required
  - [ ] Identify VCF files required
  - [ ] Identify other info required e.g. multiqc.html and meta info (tumor purity, tmb, etc)
- [ ] Update Scout config

**Comment by keyvanelhami** [comment]
We are currently unable to upload WGS Balsamic analysis in Scout. The cases in following issue are going to be uploaded in Scout https://github.com/Clinical-Genomics/Cancer-project/issues/66.

See following error message:
```
[0|0|71] 1d [keyvan.elhami@hasta:~] [P_BALSAMIC] $ balsamic plugins scout --sample-config /home/proj/production/cancer/cases/hugetomcat/hugetomcat.json --customer-id cust087 --tumor TUMOR --normal NORMAL --snv-vcf vardict.pas 
balsamic hasta.scilifelab.se 2020-11-02 09:43:16 BALSAMIC.commands.base pid:98834 [INFO] Running BALSAMIC version 6.0.1
balsamic hasta.scilifelab.se 2020-11-02 09:43:16 BALSAMIC.commands.plugins.scout pid:98834 [INFO] BALSAMIC started with log level DEBUG.
balsamic hasta.scilifelab.se 2020-11-02 09:43:16 BALSAMIC.commands.plugins.scout pid:98834 [INFO] Adding scout cancer template to delivery directory
Traceback (most recent call last):
  File "/home/proj/bin/conda/envs/P_BALSAMIC/bin/balsamic", line 33, in <module>
    sys.exit(load_entry_point('BALSAMIC==6.0.1', 'console_scripts', 'balsamic')())
  File "/home/proj/bin/conda/envs/P_BALSAMIC/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_BALSAMIC/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/proj/bin/conda/envs/P_BALSAMIC/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/P_BALSAMIC/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/P_BALSAMIC/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/proj/bin/conda/envs/P_BALSAMIC/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_BALSAMIC/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/P_BALSAMIC/lib/python3.6/site-packages/BALSAMIC/commands/plugins/scout.py", line 44, in scout
    capture_kit = os.path.basename(sample_config['panel']['capture_kit'])
KeyError: 'panel'
```

**Comment by hassanfa** [comment]
Correction: Above is BALSAMIC output, and we want to move Scout config generation to `cg` from `balsamic`.

**Comment by moonso** [comment]
Yes I will start to work on that as soon as I'm finished with the delivery part

**Comment by keyvanelhami** [comment]
Is there a way to upload Balsamic-wgs sample in Scout while waiting for cg? I have several cases in ticket 300186 that needs to be uploaded to Scout

**Comment by northwestwitch** [comment]
Hi, you could always create a scout config file manually. I don't have access to any the cancer analyses but take a look at the config file of some previous cancer case already uploaded and try to create something similar.

**Comment by keyvanelhami** [comment]
@northwestwitch Have we uploaded WGS cancer samples before in Balsamic? @hassanfa do you have any example yaml-file?

**Comment by hassanfa** [comment]
These four WGS cases are uploaded to Scout: https://github.com/Clinical-Genomics/Cancer-project/issues/30
