### ISSUE TITLE
Error while uploading cases to scout

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/cg#688]
On behalf of scout prod team. Case scenario is you want to upload easypug. You run `cg upload -f easypug`

You get this error:

```
cg upload -f easypug
----------------- UPLOAD ----------------------
Traceback (most recent call last):
 File "/home/proj/bin/conda/envs/P_main/bin/cg", line 11, in <module>
  sys.exit(base())
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 722, in __call__
  return self.main(*args, **kwargs)
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 697, in main
  rv = self.invoke(ctx)
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
  return _process_result(sub_ctx.command.invoke(sub_ctx))
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1043, in invoke
  return Command.invoke(self, ctx)
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 895, in invoke
  return ctx.invoke(self.callback, **ctx.params)
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
  return callback(*args, **kwargs)
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
  return f(get_current_context(), *args, **kwargs)
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/upload/base.py", line 71, in upload
  f"The upload started at {analysis_obj.upload_started_at} "
cg.exc.AnalysisUploadError
```

**Comment by northwestwitch** [comment]
The error is not happening for all cases. But for some, like this one

**Comment by karlnyr** [comment]
$ cg upload -f righttuna
----------------- UPLOAD ----------------------
Traceback (most recent call last):
  File "/home/proj/bin/conda/envs/P_main/bin/cg", line 11, in <module>
    sys.exit(base())
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/upload/base.py", line 71, in upload
    f"The upload started at {analysis_obj.upload_started_at} "
cg.exc.AnalysisUploadError

**Comment by moonso** [comment]
@Clinical-Genomics/production this is getting a bit old, is it still a problem? Do you know anything more @northwestwitch @karlnyr ? Please close if upload is working

**Comment by northwestwitch** [comment]
I'm not aware if this problem is still actual

**Comment by moonso** [comment]
Ok let's close and reopen if it pops up again
