### ISSUE TITLE
Chronic: start of MIP analysis for case lightkoi fails

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/cg#689]
**Cron <hiseq.clinical@hasta> $CRONIC ${PRODUCTION_HOME}/servers/resources/hasta.scilifelab.se/crontabs/workflow-mip-dna-start.sh >> ${LOG_BASE}/cg.workflow-mip-dna-start.log 2> >(tee -a ${LOG_BASE}/cg.workflow-mip-dna-start.log >&2)**

[Cron _hiseq.clinical@hasta_ $CRONIC ${PRODUCTION_HOME}_servers_resources_hasta.scilifelab.se_crontabs_workflow-mip-dna-start.sh __ ${LOG_BASE}_cg.workflow-mip-dna-start.log 2_ _(tee -a ${LOG_BASE}_cg.workflow-mip-dna-start.log _&2).zip](https://github.com/Clinical-Genomics/cg/files/4912443/Cron._hiseq.clinical%40hasta_.CRONIC.PRODUCTION_HOME._servers_resources_hasta.scilifelab.se_crontabs_workflow-mip-dna-start.sh.__.LOG_BASE._cg.workflow-mip-dna-start.log.2_._.tee.-a.LOG_BASE._cg.workflow-mip-dna-start.log._.2.zip)
```
Cronic detected failure for the command:
/home/proj/production/servers/resources/hasta.scilifelab.se/crontabs/workflow-mip-dna-start.sh

2020-07-13 12:15:13 hasta.scilifelab.se cg.cli.workflow.mip_dna.base[169593] WARNING amazedbuck: contains non-dna samples, skipping
2020-07-13 12:15:14 hasta.scilifelab.se cg.cli.workflow.mip_dna.base[169593] WARNING valuedcattle: contains non-dna samples, skipping
2020-07-13 12:15:14 hasta.scilifelab.se cg.cli.workflow.mip_dna.base[169593] WARNING pickedlark: contains non-dna samples, skipping
2020-07-13 12:15:14 hasta.scilifelab.se cg.cli.workflow.mip_dna.base[169593] INFO proudbird: start analysis
2020-07-13 12:15:14 hasta.scilifelab.se cg.meta.workflow.mip_dna[169593] WARNING H2TF5CCXX: {flowcell_obj.status}
2020-07-13 12:15:14 hasta.scilifelab.se cg.cli.workflow.mip_dna.base[169593] WARNING proudbird: not ready to run
2020-07-13 12:15:14 hasta.scilifelab.se cg.cli.workflow.mip_dna.base[169593] WARNING purerodent: contains non-dna samples, skipping
2020-07-13 12:15:14 hasta.scilifelab.se cg.cli.workflow.mip_dna.base[169593] WARNING equaltuna: contains non-dna samples, skipping
2020-07-13 12:15:14 hasta.scilifelab.se cg.cli.workflow.mip_dna.base[169593] WARNING fondkit: contains non-dna samples, skipping
2020-07-13 12:15:14 hasta.scilifelab.se cg.cli.workflow.mip_dna.base[169593] INFO comicspider: start analysis
2020-07-13 12:15:14 hasta.scilifelab.se cg.meta.workflow.mip_dna[169593] WARNING HL2M5CCXY: {flowcell_obj.status}
2020-07-13 12:15:14 hasta.scilifelab.se cg.cli.workflow.mip_dna.base[169593] WARNING comicspider: not ready to run
2020-07-13 12:15:14 hasta.scilifelab.se cg.cli.workflow.mip_dna.base[169593] INFO steadylynx: start analysis
2020-07-13 12:15:14 hasta.scilifelab.se cg.meta.workflow.mip_dna[169593] WARNING HV7VJCCXY: {flowcell_obj.status}
2020-07-13 12:15:14 hasta.scilifelab.se cg.cli.workflow.mip_dna.base[169593] WARNING steadylynx: not ready to run
2020-07-13 12:15:14 hasta.scilifelab.se cg.cli.workflow.mip_dna.base[169593] INFO savedrabbit: start analysis
2020-07-13 12:15:14 hasta.scilifelab.se cg.meta.workflow.mip_dna[169593] WARNING HNVFVCCXY: {flowcell_obj.status}
2020-07-13 12:15:14 hasta.scilifelab.se cg.cli.workflow.mip_dna.base[169593] WARNING savedrabbit: not ready to run
2020-07-13 12:15:14 hasta.scilifelab.se cg.cli.workflow.mip_dna.base[169593] INFO caringgrub: start analysis
2020-07-13 12:15:14 hasta.scilifelab.se cg.meta.workflow.mip_dna[169593] WARNING HM3VHCCXX: {flowcell_obj.status}
2020-07-13 12:15:14 hasta.scilifelab.se cg.cli.workflow.mip_dna.base[169593] WARNING caringgrub: not ready to run
2020-07-13 12:15:14 hasta.scilifelab.se cg.cli.workflow.mip_dna.base[169593] WARNING setkoi: contains non-dna samples, skipping
2020-07-13 12:15:14 hasta.scilifelab.se cg.cli.workflow.mip_dna.base[169593] WARNING indragon: contains non-dna samples, skipping
2020-07-13 12:15:14 hasta.scilifelab.se cg.cli.workflow.mip_dna.base[169593] WARNING expertmacaw: contains non-dna samples, skipping
2020-07-13 12:15:14 hasta.scilifelab.se cg.cli.workflow.mip_dna.base[169593] WARNING movingmoth: contains non-dna samples, skipping
2020-07-13 12:15:14 hasta.scilifelab.se cg.cli.workflow.mip_dna.base[169593] WARNING newyak: contains non-dna samples, skipping
2020-07-13 12:15:14 hasta.scilifelab.se cg.cli.workflow.mip_dna.base[169593] WARNING equalmouse: contains non-dna samples, skipping
2020-07-13 12:15:14 hasta.scilifelab.se cg.cli.workflow.mip_dna.base[169593] WARNING holyglider: contains non-dna samples, skipping
2020-07-13 12:15:14 hasta.scilifelab.se cg.cli.workflow.mip_dna.base[169593] INFO lightkoi: start analysis
2020-07-13 12:15:14 hasta.scilifelab.se trailblazer.mip.config[169593] ERROR ACC6989A1 -> sample_display_name: Unknown field.
2020-07-13 12:15:14 hasta.scilifelab.se trailblazer.mip.config[169593] INFO setting 'unknown' phenotype to 'unaffected'
2020-07-13 12:15:14 hasta.scilifelab.se cg.cli.workflow.mip_dna.base[169593] INFO saved config to /home/proj/production/rare-disease/cases/lightkoi/pedigree.yaml
2020-07-13 12:15:14 hasta.scilifelab.se cg.cli.workflow.get_links[169593] INFO Link all samples in a case
2020-07-13 12:15:14 hasta.scilifelab.se cg.cli.workflow.mip_dna.base[169593] INFO ACC6989A1: fastq link FASTQ files
2020-07-13 12:15:14 hasta.scilifelab.se scout.adapter.mongo.panel[169593] INFO Fetching gene panels ENDO from database
2020-07-13 12:15:14 hasta.scilifelab.se scout.adapter.mongo.panel[169593] INFO Fetching gene panels EP from database
2020-07-13 12:15:14 hasta.scilifelab.se scout.adapter.mongo.panel[169593] INFO Fetching gene panels IEM from database
2020-07-13 12:15:15 hasta.scilifelab.se scout.adapter.mongo.panel[169593] INFO Fetching gene panels IBMFS from database
2020-07-13 12:15:15 hasta.scilifelab.se scout.adapter.mongo.panel[169593] INFO Fetching gene panels mtDNA from database
2020-07-13 12:15:15 hasta.scilifelab.se scout.adapter.mongo.panel[169593] INFO Fetching gene panels MIT from database
2020-07-13 12:15:15 hasta.scilifelab.se scout.adapter.mongo.panel[169593] INFO Fetching gene panels PEDHEP from database
2020-07-13 12:15:15 hasta.scilifelab.se scout.adapter.mongo.panel[169593] INFO Fetching gene panels OMIM-AUTO from database
2020-07-13 12:15:15 hasta.scilifelab.se scout.adapter.mongo.panel[169593] INFO Fetching gene panels PIDCAD from database
2020-07-13 12:15:15 hasta.scilifelab.se scout.adapter.mongo.panel[169593] INFO Fetching gene panels PID from database
2020-07-13 12:15:15 hasta.scilifelab.se scout.adapter.mongo.panel[169593] INFO Fetching gene panels SKD from database
2020-07-13 12:15:15 hasta.scilifelab.se scout.adapter.mongo.panel[169593] INFO Fetching gene panels NMD from database
2020-07-13 12:15:15 hasta.scilifelab.se scout.adapter.mongo.panel[169593] INFO Fetching gene panels CTD from database
2020-07-13 12:15:15 hasta.scilifelab.se scout.adapter.mongo.panel[169593] INFO Fetching gene panels IF from database
2020-07-13 12:15:15 hasta.scilifelab.se scout.adapter.mongo.panel[169593] INFO Fetching gene panels NEURODEG from database
2020-07-13 12:15:15 hasta.scilifelab.se scout.adapter.mongo.panel[169593] INFO Fetching gene panels mcarta from database
2020-07-13 12:15:15 hasta.scilifelab.se scout.adapter.mongo.panel[169593] INFO Fetching gene panels Cardiology from database
2020-07-13 12:15:15 hasta.scilifelab.se scout.adapter.mongo.panel[169593] INFO Fetching gene panels BRAIN from database
2020-07-13 12:15:15 hasta.scilifelab.se scout.adapter.mongo.hgnc[169593] INFO Building hgncid_to_gene
[INFO] 2020/07/13 12:15:29 MIP_ANALYSE - MIP Version: v8.2.6
[INFO] 2020/07/13 12:15:29 MIP_ANALYSE - Script parameters and info from are saved in file: /home/proj/production/rare-disease/cases/lightkoi/analysis/mip_log/2020-07-13/mip_2020-07-13T12:15:29.log
[INFO] 2020/07/13 12:15:29 MIP_ANALYSE - Loaded: /home/proj/production/rare-disease/cases/lightkoi/pedigree.yaml
 [31m[FATAL] 2020/07/13 12:15:29 MIP_ANALYSE - Could not find intended infile_dirs directory: /home/proj/production/rare-disease/cases/lightkoi/wgs/ACC6989A1/fastq [0m


Traceback (most recent call last):
  File "/home/proj/bin/conda/envs/P_main/bin/cg", line 11, in <module>
    sys.exit(base())
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/workflow/mip_dna/base.py", line 204, in start
    context.invoke(mip_dna, priority=priority, case_id=case_obj.internal_id)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/workflow/mip_dna/base.py", line 71, in mip_dna
    run, case_id=case_id, priority=priority, email=email, start_with=start_with,
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/workflow/mip_dna/base.py", line 172, in run
    context.obj["api"].run(case_obj, priority=priority, email=email, start_with=start_with)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/meta/workflow/mip_dna.py", line 105, in run
    self.tb.run(family_obj.internal_id, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/apps/tb/api.py", line 50, in run
    self.mip_cli(**kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/trailblazer/mip/start.py", line 37, in __call__
    process = self.execute(command)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/trailblazer/mip/start.py", line 62, in execute
    process = subprocess.run(" ".join(command), shell=True, check=True)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/subprocess.py", line 481, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'bash -c 'source activate P_mip8.2_rd-dna;  /home/proj/bin/conda/envs/P_mip8.2_rd-dna/bin/mip analyse rd_dna lightkoi --config_file /home/proj/production/servers/config/hasta.scilifelab.se/mip8.2.yaml --slurm_quality_of_service low '' returned non-zero exit status 1.

RESULT CODE: 1
```

**Comment by talnor** [comment]
This data was delivered to cust as fastq. Changed 'Data analysis' in statusDB from fastq -> MIP to start analysis. Then changed it back to fastq after starting the analysis.

**Comment by barrystokman** [comment]
What should we do so the automation doesn't pick it up again and/or throws an error?

**Comment by talnor** [comment]
We want to run MIP for these cases to compare results with MAF. Would it be possible to allow starting MIP on samples that have 'Data Analysis'=fastq as well?

**Comment by barrystokman** [comment]
Maybe we can add an option or flag to manually trigger analysis in those cases.

**Comment by henrikstranneheim** [comment]
I also think that this will be properly solved when we separate `analysis` (mip, balsamic etc) from `delivery` (fastqc, scout, etc). I have asked @patrikgrenfeldt to start looking into splitting these fields from the order portal and let it propagate to the rest of the system.
