### ISSUE TITLE
Cron <hiseq.clinical@hasta> $CRONIC ${PRODUCTION_HOME}/servers/resources/hasta.scilifelab.se/crontabs/upload-auto.sh >> ${LOG_BASE}/cg.upload.log 2> >(tee -a ${LOG_BASE}/cg.upload.log >&2)

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/cg#691]
**Cron <hiseq.clinical@hasta> $CRONIC ${PRODUCTION_HOME}/servers/resources/hasta.scilifelab.se/crontabs/upload-auto.sh >> ${LOG_BASE}/cg.upload.log 2> >(tee -a ${LOG_BASE}/cg.upload.log >&2)**

[Cron _hiseq.clinical@hasta_ $CRONIC ${PRODUCTION_HOME}_servers_resources_hasta.scilifelab.se_crontabs_upload-auto.sh __ ${LOG_BASE}_cg.upload.log 2_ _(tee -a ${LOG_BASE}_cg.upload.log _&2).zip](https://github.com/Clinical-Genomics/cg/files/4912440/Cron._hiseq.clinical%40hasta_.CRONIC.PRODUCTION_HOME._servers_resources_hasta.scilifelab.se_crontabs_upload-auto.sh.__.LOG_BASE._cg.upload.log.2_._.tee.-a.LOG_BASE._cg.upload.log._.2.zip)

**Comment by barrystokman** [comment]
@henningonsbring @karlnyr There's a lot of upload exceptions raised, and we receive these emails daily. The exception is raised when the upload isn't finished within 24 hours:

```
if not force_restart and analysis_obj.upload_started_at is not None:
            if dt.datetime.now() - analysis_obj.upload_started_at > dt.timedelta(hours=24):
                raise AnalysisUploadError(
                    f"The upload started at {analysis_obj.upload_started_at} "
                    f"something went wrong, restart it with the --restart flag"
                )
```

Are you restarting these with the --restart flag? Do you know whjy these are failing?

@eriksjolund there also a lot of errors `sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1040, 'Too many connections') (Background on this error at: http://sqlalche.me/e/e3q8)`, see example below. Do you know what could cause this?

```
2020-07-13 12:55:28 hasta.scilifelab.se cg.cli.upload.base[193298] INFO uploading family: soliddingo
----------------- UPLOAD ----------------------
2020-07-13 12:55:29 hasta.scilifelab.se cg.cli.upload.base[193298] ERROR uploading family failed: 


2020-07-13 12:55:29 hasta.scilifelab.se cg.cli.upload.base[193298] ERROR Traceback (most recent call last):
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2228, in _wrap_pool_connect
    return fn()
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/pool.py", line 425, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/pool.py", line 822, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/pool.py", line 554, in checkout
    rec = pool._do_get()
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/pool.py", line 1250, in _do_get
    self._dec_overflow()
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 67, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 277, in reraise
    raise value
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/pool.py", line 1247, in _do_get
    return self._create_connection()
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/pool.py", line 370, in _create_connection
    return _ConnectionRecord(self)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/pool.py", line 499, in __init__
    self.__connect(first_connect_check=True)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/pool.py", line 701, in __connect
    connection = pool._invoke_creator(self)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 437, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/pymysql/connections.py", line 599, in connect
    self._request_authentication()
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/pymysql/connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1040, 'Too many connections')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/upload/base.py", line 162, in auto
    context.invoke(upload, family_id=internal_id)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/upload/base.py", line 50, in upload
    family_obj = context.obj["status"].family(family_id)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/store/api/findbusinessdata.py", line 117, in family
    return self.Family.query.filter_by(internal_id=internal_id).first()
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2979, in first
    ret = list(self[0:1])
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2771, in __getitem__
    return list(res)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3081, in __iter__
    return self._execute_and_instances(context)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3103, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3111, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3096, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1120, in connection
    execution_options=execution_options,
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1126, in _connection_for_bind
    engine, execution_options
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 424, in _connection_for_bind
    conn = bind.contextual_connect()
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2192, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2232, in _wrap_pool_connect
    e, dialect, self
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1528, in _handle_dbapi_exception_noconnection
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 276, in reraise
    raise value.with_traceback(tb)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2228, in _wrap_pool_connect
    return fn()
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/pool.py", line 425, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/pool.py", line 822, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/pool.py", line 554, in checkout
    rec = pool._do_get()
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/pool.py", line 1250, in _do_get
    self._dec_overflow()
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 67, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 277, in reraise
    raise value
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/pool.py", line 1247, in _do_get
    return self._create_connection()
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/pool.py", line 370, in _create_connection
    return _ConnectionRecord(self)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/pool.py", line 499, in __init__
    self.__connect(first_connect_check=True)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/pool.py", line 701, in __connect
    connection = pool._invoke_creator(self)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 437, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/pymysql/connections.py", line 599, in connect
    self._request_authentication()
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/pymysql/connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1040, 'Too many connections') (Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by karlnyr** [comment]
I would not dare to say that this is the error that we have been occurring a lot lately, do you have some example families where this has occurred? 

To recap our latest issues, there are a lot of cases that already have an old run existing, in many of those cases the statusdb saves the uploaded date for that case. Here, we remove the scout yaml file in the analysis folder and restart with the --restart flag. I know that Emma S previously also circumvented the problem by removing the "analysis uploaded at" in statusdb, which allowed for upload to Scout.

**Comment by barrystokman** [comment]
There's a mail to clinical-logwatch today at 9:55 that has the most recents examples.

To allow re-uploads, it seems we want to reset the upload_started_at date after the uploaded_at date has been filled. Not sure if we need a check to prevent unwanted re-uploads, but I can lok into it.

**Comment by karlnyr** [comment]
Just read it, I know that there are a lot of old cases, that I guess are stored in housekeeper, that for some reason are getting pinged for upload. I don't know whether we want this or not. Otherwise, I think your check sounds good.

**Comment by barrystokman** [comment]
Draft PR https://github.com/Clinical-Genomics/cg/pull/695, will add tests later.

**Comment by henrikstranneheim** [comment]
I do not think we are seeing this type of errors anymore. Closing this - please reopen if you disagree
