### ISSUE TITLE
Error retrieving bed path for GMSmyeloid5.2 in BALSAMIC

### ISSUE THREAD

**Issue by Mropat** [Clinical-Genomics/cg#701]
Problem: 
When running balsamic workflows with cg, submitting jobs for samples where capture kit is GMSmyeloid5.2 fails with LimsDataError

Likely culprit:
Panel name returned from LIMS ("gms-myeloid_5.2"), is different from available shortnames for GMSmyeloid5.2 in StatusDB:
GMSmyeloid5.2, gms_myeloid_5.2 

Traceback:
```
ACC6970A1 application type is tgs
ACC6970A1: config FASTQ file
Traceback (most recent call last):
  File "/home/proj/bin/conda/envs/P_main/bin/cg", line 11, in <module>
    sys.exit(base())
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/workflow/balsamic/base.py", line 59, in balsamic
    context.invoke(config_case, case_id=case_id, target_bed=target_bed)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/workflow/balsamic/base.py", line 185, in config_case
    context.obj["lims_api"], context.obj["store_api"], link_obj.sample.internal_id
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/meta/workflow/base.py", line 10, in get_target_bed_from_lims
    target_bed_shortname = lims.capture_kit(target_bed)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/apps/lims/api.py", line 162, in capture_kit
    raise LimsDataError(message)
cg.exc.LimsDataError

```
Steps to reproduce
  1. Locate case requiring GMSmyeloid5.2 on stage or make one available
  2. Run cg workflow balsamic -c [CASE_ID]
  3. Observe error

Expected outcome / suggested solution:
Case starts normally.

Questions: 
Q: Does the same problem occur for other panels?
A: No

**Comment by annaengstrom** [comment]
@Mropat where is "gms-myeloid_5.2" found?

**Comment by Mropat** [comment]
@annaengstrom it is a prep category in LIMS
It is set during sample prep. Currently there are two equivalent options for this capture kit that can be set in lims. 

I have looked into this, and will need to discuss further with @mayabrandi.

**Comment by annaengstrom** [comment]
What is the UDF in LIMS and LIMS-ID?

**Comment by Mropat** [comment]
@annaengstrom ACC6970A1

**Comment by annaengstrom** [comment]
I can see that "gms_myeloid_5.2" has been set in UDF Bait Set

![Screen Shot 2020-09-04 at 11 50 00 AM](https://user-images.githubusercontent.com/36469416/92226298-cd062280-eea4-11ea-8f79-1f8cc9c8be3d.png)
