### ISSUE TITLE
Cron <hiseq.clinical@hasta> $CRONIC ${PRODUCTION_HOME}/servers/resources/hasta.scilifelab.se/crontabs/workflow-mip-dna-store-completed.sh >> ${LOG_BASE}/cg.workflow-mip-dna-store-completed.log 2> >(tee -a ${LOG_BASE}/cg.workflow-mip-dna-store-completed.log >&2)

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/cg#754]
storing family: coollamb
bundle already added
2020-09-15 06:31:18 hasta.scilifelab.se cg.cli.workflow.mip.store[103710] ERROR case storage failed: coollamb
Traceback (most recent call last):
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/workflow/mip/store.py", line 49, in analysis
    status,
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/meta/store/mip.py", line 25, in gather_files_and_bundle_in_housekeeper
    raise BundleAlreadyAddedError("bundle already added")
cg.exc.BundleAlreadyAddedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/workflow/mip/store.py", line 84, in completed
    context.invoke(analysis, config_stream=config_stream)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/workflow/mip/store.py", line 59, in analysis
    context.abort()
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 480, in abort
    raise Abort()
click.exceptions.Abort
storing family: coollamb
bundle already added
2020-09-15 06:31:19 hasta.scilifelab.se cg.cli.workflow.mip.store[103710] ERROR case storage failed: coollamb

Traceback (most recent call last):
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/workflow/mip/store.py", line 49, in analysis
    status,
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/meta/store/mip.py", line 25, in gather_files_and_bundle_in_housekeeper
    raise BundleAlreadyAddedError("bundle already added")
cg.exc.BundleAlreadyAddedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/workflow/mip/store.py", line 84, in completed
    context.invoke(analysis, config_stream=config_stream)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/workflow/mip/store.py", line 59, in analysis
    context.abort()
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/click/core.py", line 480, in abort
    raise Abort()
click.exceptions.Abort

RESULT CODE: 1

**Comment by Mropat** [comment]
This is happening, because coollamb is both a balsamic and a mip case.

When mip starts analysis, it sets the action on case in StatusDB to running. When the analysis is running, cg will periodically check if it is completed. When completed, it stores the bundle in Housekeeper and sets action to None.
This prevents the case to be eligible for automatic start with mip or balsamic in the future (Only cases without analysis, or cases with "analyze" action start automatically)
Then, I assume we have started coollamb manually for Balsamic shortly after MIP analysis was completed and stored. This sets action on the case to "running" in statusDB again. Mip workflow will periodically check all mip cases that are running and try to store them, and set action to None. But coollamb has been stored in HK already with this timestamp, so we get the error.

So this should go away once coollamb is finished with Balsamic and stored in Housekeeper. When this happens, I quite hope that the scout report for it is added to specifically the MIP version of the bundle... But something tells me it might not play out this way

**Comment by Mropat** [comment]
Coollamb should no longer be a problem
