### ISSUE TITLE
cg upload scout rerun upload fails

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/cg#946]
As an addicted person, I want to drink coffee so that I wake up.

Also, when I reupload scout cases with cg, I would like reruns to be handled properly, even in the face of missing data.

Problem: 
Eg currently, stage case deepbeagle will fail scout reupload, as it has some idea about an old rerun 2019-05-02, and will not find the config data for the latest 2020-12-03.

us
cg upload scout -r deepbeagle

Expected outcome / suggested solution:
A coffee in my cup. And a scout loaded case.

Questions: 
Q: Does the same problem occur for tea?
A: Not really, regular uploads of reruns take place so perhaps it is just missing data.

**Comment by dnil** [comment]
Looks like its just not loaded properly in houskeeper:
`housekeeper get bundle -v deepbeagle`only finds the 2019-05-02 analysis, for which files are missing. Still, would not hurt if cg gracefully said that. And exited by all means. 😄

**Comment by moonso** [comment]
Yes our stage env is very flawed unfortunately and files disappears now and then.

Could you post the stack trace?

**Comment by dnil** [comment]
Sure, and that is actually another issue. This genuinely appears to be just missing files.  Not sure yet if it happens if any (config) file is missing, if latest on housekeeper is missing, or just if none is left...

Here is a similar one from justhusky
```
[0|0|498] [daniel.nilsson@hasta:/home/proj/stage/housekeeper-bundles/justhusky/2020-11-11] [S_main] 45m57s $ cg upload scout -r justhusky
----------------- UPLOAD ----------------------
----------------- SCOUT -----------------------
----------------- CREATE CONFIG -----------------------
Fetching family object
Create load config
Generate scout load config
Fetch latest version from bundle justhusky
Found pipeline mip-dna
Generate load config for mip case
Fetch latest version from bundle justhusky
Fetching files from bundle justhusky
Fetching files with tags in [mip-config]
Fetching files from version 16939
/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/query.py:2334: SAWarning: Pathed join target File.version has already been joined to; skipping
  "been joined to; skipping" % prop
Traceback (most recent call last):
  File "/home/proj/bin/conda/envs/S_main/bin/cg", line 11, in <module>
    sys.exit(base())
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/cg/cli/upload/scout.py", line 35, in scout
    create_scout_load_config, case_id=case_id, print_console=print_console, re_upload=re_upload
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/cg/cli/upload/scout.py", line 55, in create_scout_load_config
    scout_load_config: ScoutLoadConfig = scout_upload_api.generate_config(case_obj.analyses[0])
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/cg/meta/upload/scout/scoutapi.py", line 67, in generate_config
    config_builder.build_load_config()
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/cg/meta/upload/scout/mip_config_builder.py", line 49, in build_load_config
    self.analysis_obj.family.internal_id
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/cg/meta/workflow/mip.py", line 366, in get_latest_metadata
    mip_config_raw = self._get_latest_raw_file(family_id=family_id, tag="mip-config")
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/cg/meta/workflow/mip.py", line 347, in _get_latest_raw_file
    analysis_file_raw = self._open_bundle_file(analysis_files[0].path)
  File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/cg/meta/workflow/mip.py", line 360, in _open_bundle_file
    open_file = safe_load(open(full_file_path))
FileNotFoundError: [Errno 2] No such file or directory: '/home/proj/stage/housekeeper-bundles/justhusky/2020-02-20/justhusky_config.yaml'
```

**Comment by moonso** [comment]
Yes, so I don't know if this is obvious but the files exists as database entries in housekeeper but the actual file on desk has been wiped. This is a result of our flawed stage environment where files get removed for different reasons but the databases are not updated accordingly. I can add more graceful error handling for this

**Comment by dnil** [comment]
And no rush - if it works if any - or at least the latest - is on disk then its jus Quality of Life or corresponding.

**Comment by moonso** [comment]
Could you try again @dnil ? If you get a more informative error message you could perhaps close this?

**Comment by dnil** [comment]
Sure, that sounds perfect. I misread it initially, and really think a more useful thing to work on would be like a "verify" or "cleanup" command for housekeeper.

**Comment by dnil** [comment]
Was there a particular branch you wanted me to test or just master?

**Comment by dnil** [comment]
Hm, looks the same on master, but, honestly knowing what it looks like in hk makes this this rather ok. Garbage in - garbage out. How about we just close this and possibly file an issue for housekeeper to clean it up - or add a command / script for it for cleanup?

**Comment by Mropat** [comment]
Closing. It is a problem with our staging set-up and while a pain in the ass, there is a work-around
