### ISSUE TITLE
Failure for workflow-mip-dna-store-completed.sh

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/cg#985]
## Description

Cron <hiseq.clinical@hasta> $CRONIC ${PRODUCTION_HOME}/servers/resources/hasta.scilifelab.se/crontabs/workflow-mip-dna-store-completed.sh >> ${LOG_BASE}/cg.workflow-mip-dna-store-completed.log 2> >(tee -a ${LOG_BASE}/cg.workflow-mip-dna-store-completed.log >&2)

Cronic detected failure for the command:
/home/proj/production/servers/resources/hasta.scilifelab.se/crontabs/workflow-mip-dna-store-completed.sh

```
2021-02-18 20:30:21 hasta.scilifelab.se cg.cli.workflow.mip.store[104795] ERROR Case storage failed: legalelk
Traceback (most recent call last):
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/workflow/mip/store.py", line 96, in completed
   analysis_obj = mip_api.tb.get_latest_analysis(case_id=case_obj.internal_id)
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/apps/tb/api.py", line 89, in get_latest_analysis
   response = self.query_trailblazer(command="get-latest-analysis", request_body=request_body)
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/apps/tb/api.py", line 39, in query_trailblazer
   LOG.debug(f"REQUEST HEADER {self.auth_header}")
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/apps/tb/api.py", line 31, in auth_header
   signer = RSASigner.from_service_account_file(self.service_account_auth_file)
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/google/auth/crypt/base.py", line 128, in from_service_account_file
   with io.open(filename, 'r', encoding='utf-8') as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/proj/production/servers/authentication/trailblazer-auth.json'
2021-02-18 20:30:21 hasta.scilifelab.se cg.cli.workflow.mip.store[104795] ERROR Case storage failed: justhusky
Traceback (most recent call last):
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/cli/workflow/mip/store.py", line 96, in completed
   analysis_obj = mip_api.tb.get_latest_analysis(case_id=case_obj.internal_id)
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/apps/tb/api.py", line 89, in get_latest_analysis
   response = self.query_trailblazer(command="get-latest-analysis", request_body=request_body)
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/apps/tb/api.py", line 39, in query_trailblazer
   LOG.debug(f"REQUEST HEADER {self.auth_header}")
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/cg/apps/tb/api.py", line 31, in auth_header
   signer = RSASigner.from_service_account_file(self.service_account_auth_file)
 File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/google/auth/crypt/base.py", line 128, in from_service_account_file
   with io.open(filename, 'r', encoding='utf-8') as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/proj/production/servers/authentication/trailblazer-auth.json'
```

## Prior actions leading to this bug
- The authentication files should not be on git, but present locally on Hasta, which is communicating with Trailblazervia the cg config
- The authentication files were accidentally added to the central github, and and added to `.gitignore`. However, that meant that untracked files in were left in the git stage servers repo on Hasta. The authentication files would then be deleted by git when pulling a branch to the servers git repo casuing trailblazer to crash with the error seen in the cron mail above.
- The problem is described here: https://stackoverflow.com/questions/7927230/remove-directory-from-remote-repository-after-adding-them-to-gitignore and the proposed and executed solution in servers is here: https://github.com/Clinical-Genomics/servers/issues/491. Leading to the files being removed from the central git repo: https://github.com/Clinical-Genomics/servers/commit/aa19589381c604fd6b5362aedaba161281baf07f
- When deploying this PR: https://github.com/Clinical-Genomics/servers/pull/490 the following merge conflict happened:
```
bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-servers-prod.sh
on the host hasta.scilifelab.se, continue
This will install the latest version of servers on master in production, are you sure? y/[n]y
repository is dirty
# On branch master
# Your branch is ahead of 'origin/master' by 4 commits.
#   (use "git push" to publish your local commits)
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#	config/hasta.scilifelab.se/identifier_fohmkey
#	config/hasta.scilifelab.se/identifier_fohmkey.pub
#	resources/hasta.scilifelab.se/cg/
nothing added to commit but untracked files present (use "git add" to track)
This deletes any changed/untracked files, are you sure? y/[n]y
HEAD is now at 354e223 Merge branch 'master' of https://github.com/Clinical-Genomics/servers
remote: Enumerating objects: 22, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 15 (delta 9), reused 7 (delta 4), pack-reused 0
Unpacking objects: 100% (15/15), done.
From https://github.com/Clinical-Genomics/servers
   8782445..96245b1  master     -> origin/master
 * [new tag]         v5.29.3    -> v5.29.3
Already on 'master'
Your branch and 'origin/master' have diverged,
and have 4 and 3 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
CONFLICT (modify/delete): authentication/trailblazer-auth.json deleted in 96245b1d9f64317ccf0375c0a1d2ce854315837f and modified in HEAD. Version HEAD of authentication/trailblazer-auth.json left in tree.
Removing authentication/README.md
Automatic merge failed; fix conflicts and then commit the result.
```
- This was applied to the production servers repo on Hasta: `git rm authentication/trailblazer-auth.json`
- And the files were incorrectly moved from the production servers repo causing the bug described above.

## Suggested solution

- Make sure that the authentication/trailblazer-auth.json are placed in:
  - `/home/proj/production/servers/`
  - `/home/proj/stage/servers/`
- And gitignored and not tracked by git locally or centrally

## This can be closed when

The suggested solution is in place.

```
[1|34|404] [henrik.stranneheim@hasta:/home/proj/production/servers] [S_main] master(5)* 3s ± ls -la /home/proj/production/servers/
total 0
drwxrws---+ 10 hiseq.clinical     users 4096 Feb 18 20:49 .
drwxrws---+ 18 hiseq.clinical     users 4096 Jan 27 11:32 ..
drwxrws---+  2 maryia.ropart      users 4096 Feb 18 20:48 authentication
-rw-rw----+  1 hiseq.clinical     users   60 Sep  5  2019 book.json
-rw-rw----+  1 henrik.stranneheim users   91 Feb 18 16:15 .bumpversion.cfg
drwxrws---+  9 hiseq.clinical     users 4096 Feb  2 08:00 config
drwxrws---+  3 hiseq.clinical     users 4096 Feb 15 13:58 crontab
-rw-rw----+  1 henrik.stranneheim users 2607 Jan 19 11:45 DEPLOYMENT.md
drwxrws---+  6 hiseq.clinical     users 4096 Oct 16 14:50 dotfiles
drwxrws---+  8 hiseq.clinical     users 4096 Feb 19 10:30 .git
drwxrws---+  4 hiseq.clinical     users 4096 Feb 11 09:39 .github
-rw-rw----+  1 maryia.ropart      users 1156 Oct 29 15:12 .gitignore
drwxrws---+  6 hiseq.clinical     users 4096 Oct 16 14:50 manual
-rw-rw----+  1 patrik.grenfeldt   users 1509 Feb 19  2020 README.md
drwxrws---+  7 hiseq.clinical     users 4096 Feb  2 07:47 resources
[1|34|451] [henrik.stranneheim@hasta:/home/proj/production/servers] [S_main] master(5)* ± ls -la /home/proj/stage/servers/
total 0
drwxrws---+ 10 barry.stokman      users 4096 Feb 19 08:45 .
drwxrws---+ 18 hiseq.clinical     users 4096 Feb  8 09:46 ..
drwxrws---+  2 henrik.stranneheim users 4096 Feb 19 08:45 authentication
-rw-rw----+  1 barry.stokman      users   60 Feb  8 09:46 book.json
-rw-rw----+  1 henrik.stranneheim users   91 Feb 18 16:14 .bumpversion.cfg
drwxrws---+  9 barry.stokman      users 4096 Feb 17 11:50 config
drwxrws---+  3 barry.stokman      users 4096 Feb 17 11:50 crontab
-rw-rw----+  1 henrik.stranneheim users 2607 Feb 17 11:50 DEPLOYMENT.md
drwxrws---+  6 barry.stokman      users 4096 Feb  8 09:46 dotfiles
drwxrws---+  8 barry.stokman      users 4096 Feb 19 10:29 .git
drwxrws---+  4 barry.stokman      users 4096 Feb 17 11:50 .github
-rw-rw----+  1 barry.stokman      users 1156 Feb  8 09:46 .gitignore
drwxrws---+  6 barry.stokman      users 4096 Feb  8 09:46 manual
-rw-rw----+  1 barry.stokman      users 1509 Feb  8 09:46 README.md
drwxrws---+  7 barry.stokman      users 4096 Feb  8 09:46 resources
[1|34|451] [henrik.stranneheim@hasta:/home/proj/production/servers] [S_main] master(5)* ± git status
# On branch master
# Your branch is ahead of 'origin/master' by 5 commits.
#   (use "git push" to publish your local commits)
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#	config/hasta.scilifelab.se/identifier_fohmkey
#	config/hasta.scilifelab.se/identifier_fohmkey.pub
#	resources/hasta.scilifelab.se/cg/
nothing added to commit but untracked files present (use "git add" to track)
[1|34|451] [henrik.stranneheim@hasta:/home/proj/production/servers] [S_main] master(5)* ± cd /home/proj/stage/servers/
[1|34|451] [henrik.stranneheim@hasta:/home/proj/stage/servers] [S_main] master+ ± git status
# On branch master
nothing to commit, working directory clean
```
<img width="642" alt="Screenshot 2021-02-19 at 10 47 11" src="https://user-images.githubusercontent.com/584738/108487699-d55de880-729f-11eb-8436-c3c37bfe7d72.png">

**Comment by henrikstranneheim** [comment]
The proposed solution has been performed and production and stage is working.

@Mropat Please clarify or modify this issue as you see fit so that we have good traceability if this occurs again
